### ISSUE TITLE
Upgrade from LanSuite v4.2 to v5.0-dev

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1092]
It´s mentioned [there ](https://lansuite.github.io/lansuite/docs/guides/upgrade/)to put in the following line to /inc.base.config.php
``` 
[...]
[database]
sqlmode = "NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
[...]
```
Afterwards I get the following error on the Lansuite site
```
Die Verbindung zur Datenbank ist fehlgeschlagen. LanSuite wird abgebrochen. Zurückgegebener MySQL-Fehler: Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' (1231)
```

**Comment by M4LuZ** [comment]
[there ](https://lansuite.github.io/lansuite/docs/guides/upgrade/) is sadly no longer correct as of MySQL 8.0 as option  `NO_AUTO_CREATE_USER` has been removed, related PR open in a sec
