### ISSUE TITLE
Activate / Deaktivate modules error 500

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1097]
When activating and deactivating modules i get error 500 on step 2
https://www.netsession.net/index.php?mod=install&action=modules&step=2

Apache log
```
<!--StartFragment-->
2024-04-10 18:39:10 | Error |  | 500 | POST /index.php?mod=install&action=modules&step=2 HTTP/1.0
-- | -- | -- | -- | --
<!--EndFragment-->

```

**Comment by M4LuZ** [comment]
Hi @Pimmal,

this is is most probably related and caused by the issues noted in  #1096.
I suggest to run a Git + DB upgrade and then see if the issue disappears.

**Comment by Pimmal** [comment]
This issue is also resolved.
