### ISSUE TITLE
PHP errors News archive

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1128]
Fehler:
PHP Warning: Undefined array key "sql" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/news/show.php on line 22
PHP Warning: Undefined array key "html" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/news/show.php on line 43

URL: index.php?mod=news&action=show&subaction=archive

![image](https://github.com/lansuite/lansuite/assets/20731374/38c315d7-ee50-4a62-b715-0ef006dde7dd)

**Comment by andygrunwald** [comment]
Fix prepared here: https://github.com/lansuite/lansuite/pull/1174
