### ISSUE TITLE
PHP error add news

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1129]
Fehler:
PHP Warning: Undefined array key "text" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/inc/Classes/MasterForm.php on line 758

URL: index.php?mod=news&action=add

![image](https://github.com/lansuite/lansuite/assets/20731374/b7baa7fd-8d6f-4a52-8afa-3a5ec7970783)

**Comment by andygrunwald** [comment]
@Pimmal Can you still reproduce this error with the latest master?

**Comment by andygrunwald** [comment]
PR for a fix can be found here: https://github.com/lansuite/lansuite/pull/1177
