### ISSUE TITLE
PHP error on module wiki

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1130]
Fehler:
PHP Warning: Undefined array key "name" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/wiki/show.php on line 3
PHP Warning: Undefined array key "postid" in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/wiki/show.php on line 7

URL: index.php?mod=wiki

![image](https://github.com/lansuite/lansuite/assets/20731374/330cc50c-1cec-4bfc-9eaf-e1edf756fe72)

**Comment by M4LuZ** [comment]
Hi @Pimmal ,

as I understand these are just warnings that elements are uninitialized, but the code works fine with the (assumed) standard values (unless it doesn't? Related information is missing)
.
I'll raise a separate Ticket to not show these to regular users, but just administrators, as these warnings are misleading

**Comment by andygrunwald** [comment]
Fix prepared here: https://github.com/lansuite/lansuite/pull/1175
