### ISSUE TITLE
Restrict display of PHP warnings to (Super-)Admins

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#1131]
## Expected Behavior

End users should be informed if something did not work as expected, as they need to be aware that an operation did not finish successfully as they expected. 
Otherwise information not important or relevant for them should not be shown.
Administrators are users which should have an interest in warnings and further informations, so they should receive the related information

## Current Behavior

Warnings are shown to all users that both expose internal information and potentially confuse them, as there is a red message with some PHP warning.

## Possible Solution

* Set error_level to E_WARN early in the code.
* Once ` $cfg` and `$auth` are initialized switch error level depending on user level and debug setup
* If the user is an admin OR debugging is on then leave it on E_WARN
* Otherwise switch to E_ERROR

## Steps to Reproduce (for bugs)

Find a place where a variable is not initialized, enjoy red warnings

## Context
This confuses users and leads to reports of _errors_ such as #1128, #1129, #1130

## Your Environment

* Version used:
* Operating System and version:
* Enabled features:

**Comment by andygrunwald** [comment]
Fix prepared here: https://github.com/lansuite/lansuite/pull/1172
