### ISSUE TITLE
PHP error user deletion

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1138]
Fehler:
PHP Warning: Trying to access array offset on null in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/usrmgr/Functions/CheckDeleteUser.php on line 25

But user deletion was sucessfully

URL: index.php?mod=usrmgr&action=delete&step=10

![image](https://github.com/lansuite/lansuite/assets/20731374/19841aee-6911-4bfe-b5cf-8f7c916f0d31)

Fehler:
PHP Warning: Trying to access array offset on null in /var/www/vhosts/hosting195412.ae936.netcup.net/netsession.net/httpdocs/modules/usrmgr/Functions/CheckDeleteUser.php on line 25

URL: index.php?mod=usrmgr&action=delete&step=2&userid=435

![image](https://github.com/lansuite/lansuite/assets/20731374/dea764e3-0b01-43be-896f-b9186ea6f2f3)

**Comment by andygrunwald** [comment]
Fix prepared here: https://github.com/lansuite/lansuite/pull/1176
