### ISSUE TITLE
Investigate database field "sort_tag" of "log" table: What it is doing? Usecase?

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#115]
## Expected Behavior

To be defined. Not clear yet. Goal of this issue / investigation.

## Context

In #113 @M4LuZ pointed out that the field `sort_tag` of the table `log` is only used quite less.
See https://github.com/lansuite/lansuite/pull/113/files#r160048205 for the full comment
Investigate what this field is used for or check what kind of types are in there.

**Comment by M4LuZ** [comment]
As far as I can see this only used in the Log viewer for sorting purposes and the selection list is auto-filled based on unique entries.

**Comment by M4LuZ** [comment]
@JochenJung @byte666 : Gents, can you shed some light on the usage of this field?

**Comment by JochenJung** [comment]
Usually its contains the modules name, that made the log entry. But could also be 'SQL-Fehler' (DB class) or 'LS-Fehler' (login errors, etc.) which are both module independed.

These are the distinct values of lansuite.orgapage.de:

about
Authentifikation
board
bugtracker
clanmgr
faq
guestlist
home
info2
LS-Fehler
mail
misc
news
partylist
poll
signon
SQL-Fehler
usrmgr
wiki

It is used to help find the origin of a log message.

**Comment by M4LuZ** [comment]
OK, so the module that logs the data *should* use its name or one of the general categories. But basically it is up to the implementor what value is chosen.
And the only place where the field is used is in the log viewer for filtering purposes?
That correct so far?

I would suggest to create a general function that allows logging into this, as so far this seems to be handled with direct SQL queries.

**Comment by JochenJung** [comment]
Actually as it always is the module / general class, the log function may as well set this (if it knows the current modules name).

Another place where it is used for filtering is in the bug tracker in the log tab. I'm not sure wether other modules have log tabs as well.
