### ISSUE TITLE
Trouble dumping restoring / UTF8 / Sonderzeichen not exporting or importing correctly

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#116]
Atm I have my Lansuite hosted by domainfactory. I need to move away from there but I feel unable to import the .dump file that I recieve from them.

The dump file is been created by the hoster, I can only get it as-is.

UTF encoding in the .dump file shows as follows:
!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;

When I look into the .dump file using Notepad++ and check some entrys I experience the following "replacements":
&amp;ouml; as ö
Ã¶ as ö (aswell)
&amp;szlig; as ß
Ã¤ as ä
Ã„ as Ä
Ã¼ as ü and many more.

When I rertore the dump to my XAMPP I make sure I have 

> Zeichensatz zur MySQL-Verbindung utf8mb4_german2_ci
 (I tried uft8_unicode_ci aswell)

My server has set:
> Server-Zeichensatz: UTF-8 Unicode (utf8) 

After the restore the "Umlaute" are still broken / replaced. Not only my Texts that I typed but infact all that come with Lansuite.
There are buttons like "Hinzuf├╝gen" and "G├ñsteliste".

Sadly I know nothing much about programming / SQL Queries / formatting / PHP. I am organizing LAN-Parties and build Windows Servers, that is what I can.  
I have read what feels like 16438 articles in the internet, tried each and every one and still cannot understand the nature of my problem. So I cannot help myself :/

PLEASE can anyone help me out ...

-->what am I supposed to do to replace these letters with the right one / how do I tell the import to handle it correctly?<--
Or set the database to store it correctly. Or the client to interpret it correctly or run a replace script after the import or ... you get the point ;)

I am using Lansuite 4.2, the site is hosted (now) still at PHP 5.2.17 and I want to export it from there using the domainfactory web interface (all I have sadly) and migrate / import it to:
XAMPP 7.0.6 (Apache 2.4.18, MariaDB 10.1.13, PHP 7.0.6

**Comment by M4LuZ** [comment]
Hi,

it should be sufficient to add an configuration entry to /inc/base/config.php under the database section:
named charset= "Latin1"
e.g.
`
[database]
server			= "localhost"
user				= "lansuite"
passwd			= "lansuite"
database			= "lansuite"
charset			= "Latin1"
`

There is a (german) chat about this compatibility breaking change, feel free to add your feedback as end user here: https://github.com/lansuite/lansuite/commit/f23ea4d3cc0e129ce023cf45ad2bbe33f3f63b14#diff-8b8c51bc7ea4a8bb00106a819743a8a4

**Comment by HtHNightwolf** [comment]
> I take from that that you are also moving from LS 4.2 to the current Git master?
I would love to, I copied the whole ZIP from Github to my htfiles folder, entered my custom /inc/base/config.php but nothing happened. White website, no content. I am misssing a clear How-To what to do there.

I enteres charset = "Latin1" but it makes no difference. Still "GÃ¤steliste" and such.

**Comment by andygrunwald** [comment]
We had a small email conversation with @HtHNightwolf.
He confirmed that he got his instance running on a windows server. 
He also agreed that we can close this task. If someone has the same problem, please reopen or open a new task. Thank you.
