### ISSUE TITLE
PHP notice: undefined variable

### ISSUE THREAD

**Issue by schitzN** [lansuite/lansuite#118]
Hab mir den aktuellen master geholt, lokal mit composer die dependencies installiert, auf meinen webserver geschoben und den pfad im browser eingegeben.

Zwar werden die installations-schritte angezeigt, nur sind oberhalb und unterhalb dutzende zeilen voll mit exceptions:

![unbenannt](https://user-images.githubusercontent.com/2317455/34742825-dfa35bec-f587-11e7-917a-47ddce19f5d0.JPG)
![unbenannt2](https://user-images.githubusercontent.com/2317455/34742826-dfbe0dd4-f587-11e7-8387-651ceef27315.JPG)

**Getestet mit:**
PHP 7 / PHP 7.1
MySQL 5.7

**Comment by andygrunwald** [comment]
Es scheint so als ist im error_reporting aktuell E_NOTICE aktiviert.
Dies muss deaktiviert werden. Ich kann das versuchen, morgen zu erledigen.

LanSuite ist leider nicht E_NOTICE frei.
Da ich am Wochenende ziemlich viel entwickelt habe und dieses lokal immer anhabe, muss mir das durch gerutscht sein. Sorry. Werde mich drum kümmern.

**Comment by schitzN** [comment]
Okay, danke, das heißt es sollte aber funktionieren trotz der Warnungen?

Ich kann nämlich nicht den admin-account anlegen bei der Installation. Kann das etwas mit MYSQL 5.7 zu tun haben bzw dem issue #117 ? Ich kann leider nur 5.7 installieren - was meinst du mit sql_mode umstellen?

**Comment by schitzN** [comment]
...im zweiten Bild, das ich gepostet habe sieht man einen SQL-failure.

**Comment by andygrunwald** [comment]
Wegen den PHP Notices: Das ganze wird gerade in #124 gefixt.
Das MySQL Issue werden wir dann in #117 lösen.

**Comment by M4LuZ** [comment]
Auto-Close durch merge aller verbundenen Merge requests. Denke mal, wir machen das besser zu, wenn @schitzN bestätigen kann, dass das Problem damit verschwunden ist

**Comment by M4LuZ** [comment]
@schitzN Care to comment? ;)

**Comment by M4LuZ** [comment]
Closing this now, as no feedback was provided in 3 weeks after merge of the proposed fix
