### ISSUE TITLE
Install on web-server with external db-server

### ISSUE THREAD

**Issue by mbraun81** [lansuite/lansuite#127]
Why does the DB have to run on the web server?
The first page of the install script checks if there is a local mysql server. I think it will be better to check only if a php mod for database connection is available

**Comment by andygrunwald** [comment]
The database don't have to run on the same server as the Web server.
You are able to place a configuration file into `./inc/base/config.php `.
The content is described here: https://github.com/lansuite/lansuite#configuration-file
The key `server` described the location of the server. E.g. an ip address.

If no configuration file can be found, standard configurations will be applied.
The standard configuration implies the MySQL server on localhost.
See https://github.com/lansuite/lansuite/blob/master/index.php#L218

Does this explain the behaviour? Does this help you?

**Comment by mbraun81** [comment]
Maybe then the connection of the local db on the first page of the installation should not be checked. The time at which you can enter the data would be very good for.

**Comment by M4LuZ** [comment]
Just raised a pull request for this.
It does still make sense to try to connect to the local DB instance
As that is the default setup and we're depending on that connection to check the MySQL server version. But it is certainly true, that it should not cause any issues if that initial connection fails.

(Although in theory it should be possible to determine the MySQL version without any credentials. Version number is contained in the initial packet sent by the server. Just telnet to port 3306 and have a look. But who wants to implement that?...)

**Comment by andygrunwald** [comment]
> (Although in theory it should be possible to determine the MySQL version without any credentials. Version number is contained in the initial packet sent by the server. Just telnet to port 3306 and have a look. But who wants to implement that?...)

Nice idea, but i doubt if we really need this feature. Is the information of the MySQL version really this important to put this complexity into the source code?
