### ISSUE TITLE
Tournament overview not displayed if played as league

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#142]
Originally reported on LS page: http://lansuite.orgapage.de/index.php?mod=board&action=thread&tid=1392&posts_page=0#pid7770

If a tournament is created and the mode is league then the detailed overview of the matches contains no data.  Neither team names nor match results are shown.
## Expected Behavior
Display of team names on vertical and horizontal top/left row/column
Display of match results in the table.
Link to match details per table entry
## Current Behavior

Real-Life example here: 
https://berg-lan.de/index.php?mod=tournament2&action=tree&step=2&tournamentid=45
If a tournament is created and the mode is league then the detailed overview of the matches contains no data.  Neither team names nor match results are shown.

## Possible Solution
To-be investigated. Simplest solution: Replace by simple table

## Steps to Reproduce (for bugs)

1. Create tournament with mode = league
2. Play a few matches
3. Look at the match overview

## Context

Implications are only a loss of comfort, as the match listing still works.

## Your Environment

* Version used: maluz/lansuite/HEAD (Basically 4.2 with a few fixes)
* Operating System and version: Debian 8
* Enabled features: tournament2

**Comment by rlc-gamer** [comment]
hello,
i have found a little workaround.
Open the tree.php in /modules/tourtement2/ and delete the group-variable in line 57 where the iframe is.

Change the code from
`} else $dsp->AddSingleRow('<iframe src="index.php?mod=tournament2&action=tree_frame&design=popup&tournamentid='. (int)$_GET['tournamentid'] .'&group='. (int)$_POST['group'] .'" width="100%" height="'. (int)$height .'" style="width:100%; min-width:600px;"><a href="index.php?mod=tournament2&action=tree_frame&design=base&tournamentid='. (int)$_GET['tournamentid'] .'&group='. (int)$_POST['group'] .'">Tree</a></iframe>');`

to

`  		} else $dsp->AddSingleRow('<iframe src="index.php?mod=tournament2&action=tree_frame&design=popup&tournamentid='. (int)$_GET['tournamentid'] .'" width="100%" height="'. (int)$height .'" style="width:100%; min-width:600px;"><a href="index.php?mod=tournament2&action=tree_frame&design=base&tournamentid='. (int)$_GET['tournamentid'] .'">Tree</a></iframe>');`

Also check if the tournament tree is displayed correctly.

**Comment by M4LuZ** [comment]
Hi @rlc-gamer,

thanks for your workaround, will have a look at it.
I suspect we may also remove the implicit typecasting to `(int)`here....
