### ISSUE TITLE
Unable to bring up docker container 

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#145]
Gents,

tried over the weekend to try some of our own medicine by bringing up our docker container with the documentation provided...and failed horribly.

## Expected Behavior

Follow instructions to the letter and end up with a working setup

## Current Behavior
* Requirement to run docker-compose as root not documented
* `docker-compose up` stops after bringing mysql up
* `docker-compose run php composer install`returns `Composer could not find a composer.json file in /code`

## Possible Solution

🤷‍

## Steps to Reproduce (for bugs)

$ git clone https://github.com/lansuite/lansuite.git
$ cd lansuite
$ touch ./inc/base/config.php
$ # Add the content of the example configuration file below into ./inc/base/config.php
$ chmod 0777 ./inc/base/config.php
$ chmod -R 0777 ./ext_inc/
$ docker-compose up
$ docker-compose run php composer install

## Your Environment

* Version used: origin/master
* Operating System and version: Fedora 27
* Enabled features:

**Comment by andygrunwald** [comment]
@M4LuZ 

* Can you post the logs of `docker-compose up`?
* Can you post the output of `docker version`?
* Can you post the output of `docker-compose version`?

> Requirement to run docker-compose as root not documented

I don't run this as root. And I never heard that this is necessary. But maybe there is a bug.

**Comment by M4LuZ** [comment]
Of course!

## docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64
 Experimental:    false

## docker-compose version

docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.6.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.1.0g-fips  2 Nov 2017

## docker-compose up
log output from [docker-compose.log](https://github.com/lansuite/lansuite/files/1752334/docker-compose.log) attached.

## docker-compse as root:
Running it as user returns:
```
[maluz@fedora lansuite]$ docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
But command runs fine as root. 
I'll have a look, if that is potentially usergroup-related

**Comment by andygrunwald** [comment]
I had a quick check: Even the fedora developer portal say that it runs with `sudo`: https://developer.fedoraproject.org/tools/docker/compose.html

IMO this feels wrong.
This issue says also that sudo is not necessary here: https://github.com/docker/compose/issues/4578

I found 

> Try running dockerd or sudo dockerd if required first to start daemon. If you start dockerd with sudo you may want to run docker-compose up with sudo also. otherwise it's fine.

in https://github.com/docker/compose/issues/4181#issuecomment-263501259

Can you check if the `dockerd` is running on your machine?

**Comment by M4LuZ** [comment]
There are two issues that I noted:
* docker-compose up stops after bringing mysql up. This is the more critical issue
* Some OS'es decide to restrict access to the demon socket to root only, 
See https://developer.fedoraproject.org/tools/docker/docker-installation.html . 
For these we would need to update the documentation for the installation, so that docker-compose is

**Comment by andygrunwald** [comment]
> docker-compose up stops after bringing mysql up. This is the more critical issue

According to the logs this seems to be a file permission problem:
```
...
[33mphp_1    |[0m [18-Feb-2018 21:40:51] ERROR: failed to open configuration file '/usr/local/etc/php-fpm.d/php-flags.conf': Permission denied (13)
[33mphp_1    |[0m [18-Feb-2018 21:40:51] ERROR: Unable to include /usr/local/etc/php-fpm.d/php-flags.conf from /usr/local/etc/php-fpm.conf at line 12
[33mphp_1    |[0m [18-Feb-2018 21:40:51] ERROR: failed to load configuration file '/usr/local/etc/php-fpm.conf'
[33mphp_1    |[0m [18-Feb-2018 21:40:51] ERROR: FPM initialization failed
[36mmysql_1  |[0m 2018-02-18 21:40:57 84 [Note] InnoDB: Memory barrier is not used
[36mmysql_1  |[0m 2018-02-18 21:40:57 84 [Note] InnoDB: Compressed tables use zlib 1.2.3
[32mweb_1    |[0m 2018/02/18 21:40:50 [emerg] 1#1: open() "/etc/nginx/conf.d/default.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:31
[32mweb_1    |[0m nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:31
...
```

As you can see the php and web container is also starting, but it seems that the files in `.docker`-folder is not readable for everyone.
What are your file permissions of your LanSuite clone of the `.docker` folder?

> Some OS'es decide to restrict access to the daemon socket to root only,

Can you make a PR for this and add this to the docs?
I don't have the case, I think you are the better person here to document this.

**Comment by M4LuZ** [comment]
Closing this as the issue has been identified and documentation has been updated to reflect this
