### ISSUE TITLE
Should presence of php-snmp be enforced by composer?

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#148]
## Expected Behavior

As the PHP module SNMP is only required for the network module (which has questionable functionality at the moment) I would suggest that presence is not enforced by composer.

## Current Behavior

`composer up` stops when PHP SNMP module is not present and activated

## Possible Solution
As presence is also checked during initial setup (as optional component) it is not required to enforce this in composer also. Sadly there is not (yet) an option to define requirements as optional in composer, so the decision would be in or out...

## Steps to Reproduce (for bugs)

run `composer up` after checkout without having the SNMP module active

**Comment by andygrunwald** [comment]
Good catch.
In this regard: What about the network module in general? You said it has "questionable functionality". Should we get rid of it or do you still want to keep it?

If the functionality is not useful or working at all, what benefit do we have to keep it?

**Comment by M4LuZ** [comment]
I meant questionable as I never used it and I'm unsure about its relevance and functionality 🤷‍♂️

**Comment by mbraun81** [comment]
get rid of it. There are many better modules to spend your time with fixing issues

**Comment by andygrunwald** [comment]
Checkout #154
