### ISSUE TITLE
(Frage) Workflow Internet -> Intranet

### ISSUE THREAD

**Issue by mbraun81** [lansuite/lansuite#151]
Moin,
Erst mal kurz die Story:
ich dachte mir vorhin so: Hey cool, die Installation kann man ja auch fürs Intranet machen. Auf der letzten Lan gabs ja ein paar Probleme mit dem Internet also setz ich mal ne VM auf und lasse die solange zum testen einfach mal auf die gleiche DB schreiben. Die werden ja schon in der Config Datei einen Unterschied zwischen den Installationen machen .... Öhhhm wie die Leute können sich gerade nicht Anmelden? Oh die Internet Seite steht auf Intranet? hmm das is ja mal doof gelaufen.
Nun zur Frage:

Habt ihr irgendwo ein "Best practice" zum Umgang mit Lansuit? Auch wie händelt ihr das mit dem DB abgleich vor/während der Lan für die Intranet Installation etc. Oder gibt es da gar kein richtiges DB-Konzept für?

**Comment by M4LuZ** [comment]
Moin,

kann nicht aus eigener Erfahrung berichten, da wir seit Jahren auch auf der Party die Internet-Instanz nutzen.
Mit passenden QoS auf vorhandener Leitung oder Out-of-Band mit separater Leitung oder einem Notfall-Fallback (Tethering per LTE) ging das bis jetzt eigentlich immer....
Da LS die Einstellung intern/extern in der DB ablegt, geht dein Aufbau natürlich in die Hose.

AFAIK(!) ist der Prozess folgendermaßen:
* Separate Intranet-Instanz aufsetzen
* Freeze-Mode bei Internet-Instanz an 
* DB-Export des Internet-Systems
* Import des Dumps ins Intranet-System
* Party!
* Export aus dem Intranet-System (Auswahl der relevanten Module durchdenken!)
* Import des Dumps ins Internet-System
* Freeze-Mode im Internet-System aus

**Comment by andygrunwald** [comment]
Selbes für mich. Auf unseren LAN-Parties haben wir i.d.R. Internet. Deswegen kann ich dir leider nicht sagen, in welchem Stand die Funktionalität ist.

**Comment by mbraun81** [comment]
Ok, danke für die Intos. Wir haben zwar auch Internet aber ein Plan B ist ja nie verkehrt. Auf der letzten liefen die LTE Router auch leider erst recht spät, so dass die Turniere teils mit Zettel und Stift angefangen haben.

**Comment by mbraun81** [comment]
Ja, ich denke das ist dann so weit erst mal durch, danke.

**Comment by andygrunwald** [comment]
Okay, super. Ich schließe das Ticket dann mal.
Wenn du noch was hast, meld dich einfach.
