### ISSUE TITLE
Sign up for tournaments if a user didn't have paid

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#152]
It might be useful to be able to sign up for a tournament, even if the user didn't have paid so far.
This could be a feature.

## Expected Behavior

The user is able to register for a tournament (even if he not paid for a LAN)

## Current Behavior

The user is not able to register for a tournament until he paid.

## Possible Solution

If the admin creates a tournament, it should be an option if the tournament allows users to register that doesn't have paid.

## Context

Part of the code that needs to be touched: https://github.com/lansuite/lansuite/blob/master/modules/tournament2/class_team.php#L126

## Your Environment

* Version used: Master (48a88bae)

**Comment by M4LuZ** [comment]
Hi @andygrunwald ,

can you please detail the use-case here?
I rather see that this causes an increase of an issue that we already see during our parties:
Users register for a tournament, even causing it to reach the participation user limit, but then fail to play the matches. 
If we also allow users that may never appear at the party, then this will increase again.
This could be partially mitigated (as users still initially block participation slots) by including a clean-up functionality to remove all unpaid users.
That could be then triggered either by hand or just before matches are being generated

**Comment by andygrunwald** [comment]
> If we also allow users that may never appear at the party, then this will increase again.

I agree here. The idea was to make this as a checkbox which is default checked and the checkbox is described as "Users need to have paid, because be able to register for this tournament".

The usecase are not bigger lanparties. The usecase is more for smaller lan parties with friends only where the money is collected by walking around.
We do this from time to time this way, that is where the usecase come from.

**Comment by M4LuZ** [comment]
> The usecase is more for smaller lan parties with friends only where the money is collected by walking around.
We do this from time to time this way, that is where the usecase come from.

There is an option to automatically set users to paid on registration (Partys->Mod-Config).
That would also do the trick for you, wouldn't it?

**Comment by andygrunwald** [comment]
Oh, didn't saw this. Thanks! Then this feature is complete :)
