### ISSUE TITLE
Add HTTP security headers

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#179]
## Expected Behavior

Over the last years a good amount of security enhancements have been included into the HTTP standard. Some of them are configured by the server sending defined HTTP header bits.
Thus we should have a look if we can implement these without breaking current functionality.
Examples would be:
* X-Frame-Options
* X-XSS-Protection
* X-Content-Type-Options
* Strict-Transport-Security 

More to be found for example at the [OWASP Secure Headers Project](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers)
## Current Behavior

Headers aren't set. Default Browser options are used

## Possible Solution

Set headers per default to recommended setting, fix compatibilty issues if possible, change header value otherwise

## Context

To get LS up to the current state-of-the-art in this regard

**Comment by andygrunwald** [comment]
Agree here.
Also check out this: https://getpocket.com/a/read/1990189988

**Comment by M4LuZ** [comment]
Sorry senor, me no pocket :)

**Comment by andygrunwald** [comment]
Oh sorry.
Here is the correct link: [The 2018 Guide to Building Secure PHP Software](https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software)
Fixed it also above

**Comment by M4LuZ** [comment]
Definitively a good read.
You may have noticed that I'm now using your own sources against you ;)

**Comment by andygrunwald** [comment]
This is fine as long as is it a good discussion, because i believe such discussions lead to a better end result :)

**Comment by M4LuZ** [comment]
_(removing from milestone, as not critical and no feedback received so far)_
