### ISSUE TITLE
Registration form not shown from rev. 3dcdd895 onward

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#180]
## Expected Behavior
Full registration form should be shown when trying to register under `/index.php?mod=signon`

## Current Behavior

User registration form not shown after application of refactoring of class_masterform.php from #160 

## Possible Solution

Find out what went wrong between revisions and fix the regression

## Steps to Reproduce (for bugs)

Run  `git checkout 3dcdd895` => User registration shows no form
Run `git checkout a632ed9e` => User registraton form shows up again

## Context

This seems to be a regression introduced through code refactoring.

**Comment by M4LuZ** [comment]
Really scratching my head on this.
None of the changes should influence the functionality.
Even reverting the most probable candidates (e.g.. changes to `AddField`) did not fix the issue.
More investigation needed

**Comment by andygrunwald** [comment]
What? Strange.
If i find the time, i will dive into it in the next days

**Comment by andygrunwald** [comment]
Fix prepared in https://github.com/lansuite/lansuite/pull/182

**Comment by M4LuZ** [comment]
Damn, so obvious if you know where to look :/
Thanks a bunch for catching that!
