### ISSUE TITLE
Partial MariaDB incompatibility

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#185]
## Expected Behavior

User should be added to the DB after filling out the registration form

## Current Behavior

Insert query into table `users` seems to fail, because default DB schema defines no default value for `lastlogin` and newer versions of MySQL / MariaDB seem to require that

## Possible Solution
Either:
* Update db.xml to reflect this (with a default value or CURRENT_TIMESTAMP)
or:
* add code to insert current datetime into the query
## Steps to Reproduce (for bugs)

* Run Mariadb 5.5 (or potentially MySQL 5.7 / 8.0)
* Try to register a new user

## Context

Unable to register new users. 
Unable to trial functionality to fix #96 

## Your Environment

* Version used: git/master
* Operating System and version: Fedora 27  / MariaDB 5.5 (!)
* Enabled features: N/A

**Comment by M4LuZ** [comment]
Marking this as enhancement instead of a bug as this seems to be MariaDB-related, which is not a (yet) supported DB system

**Comment by Pimmal** [comment]
I can not make sucomments on your comments therefore a normal comment.
@M4LuZ i have now moved the site to my own hosting server were MariaDB is running, i can not see such problem. For me all is fine.
`MariaDB Version 10.1.26-MariaDB-0+deb9u1 gefunden`

**Comment by M4LuZ** [comment]
Interesting. Must be an issue with my test setup then.
Thanks a bunch for the feedback!

I'll close this then and re-open if we ever see the issue re-appear

**Comment by M4LuZ** [comment]
this was (most probably) fixed with #392
