### ISSUE TITLE
Switch language of documentation, development, communication to english

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#2]
Most of the communication of the LANSuite system is / was done in German.
E.g. in the demo page, documentation or bug tracker at http://lansuite.orgapage.de/

The system LANSuite is mostly spreaded in the DACH area.

## Suggestion
My suggestion is to switch the official language to *english* for everything like

* Documentation
* Source code comments
* Bug tracking issues / discussions
* and all other topics that affects this project

## Why should we do this?
There are a few reasons why this can be beneficial:

* This might attract more endusers who using this system
* This might attract more contributor to apply pull requests to the system
* This is kind of the common standard for open source projects world wide

## What about the language barrier?
Yes, there might be a language barrier for non native speakers.
In the OSS world this is common and accepted.
I never met a person who said negative points about not to use a proper time or grammar.
So people will overlook those errors and even might be able to help you to eliminate this language barrier over time to fix typos or grammar issues.

## How do we come to a conclusion to solve this ticket?
In my opinion this has to be a decision of the main contributors. I would encourage them to post their **+1 for english** or a **-1 for stay with german** here.

**Comment by andygrunwald** [comment]
Update: @M4LuZ is fine with this as well. He agreed to this in a private email conversation.

**Comment by M4LuZ** [comment]
I rather have no strong feelings either way. We should be fine with English as documentation and development language, but it may be beneficial to keep German as valid language for any communication towards/with the end users as they are the current target audience

**Comment by andygrunwald** [comment]
That is fine for me :)
In my opinion this ticket is clarified and can be closed.
I don't think that we need to document it in the readme, because this is more or less the standard here on github.

**Comment by byte666** [comment]
Also eine englische Doku ist ok... hab ich auch eine Zeitlang versucht aber irgendwann wars für mich Sinnfrei weil in den 14 Jahren wo ich schon mitmische genau 2 Leute aus dem erweiterten EP-Raum in EN nachgefragt haben. Allgemeine Kommunikation muss ich aber sagen hab ich keinen Bock das komplizierte Zeug aus der Lansuite auch noch auf EN durchzukauen. Die Lansuite wird kein Kaliber Wordpress mehr, den Zug haben wir verpasst.

**Comment by andygrunwald** [comment]
@byte666 Wie @M4LuZ ja schon geschrieben hat. Deutsch kann als Sprache zur Kommunikation auch genutzt werden. Doku dann auch englisch.
