### ISSUE TITLE
Class name conflict between foodcenter and cashmgr

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#213]
## Expected Behavior
Issue documented here: http://lansuite.orgapage.de/index.php?mod=bugtracker&bugid=1152&ms_page=0

## Current Behavior
Both modules chashmgr and foodcenter use a class "accounting".
As both don't use a namespace, class definitions collide if both are included during execution

## Possible Solution

We could either:
* Implement proper namespacing
* Rename one of the classes
* Rework both into a general "accounting" class

**Comment by andygrunwald** [comment]
Good catch.
Let me see if i can do this quick.
