### ISSUE TITLE
Remove Code related to LanSurfer.com

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#222]
## Context

LanSuite is able to import data from LanSurfer.com.
@M4LuZ suggested to remove the code, because the project died in 2006.
See https://github.com/lansuite/lansuite/pull/219#pullrequestreview-116159855

## Expected Behavior

Remove every piece of code related to LanSurfer.com functionality.

## Your Environment

* Version used: LanSuite master (rev 4d69017)
* Operating System and version: every

**Comment by M4LuZ** [comment]
"It's not a bug, it's a (dead) feature!"
