### ISSUE TITLE
Fatal error bei Neuer Lansuite Installation auf Webserver (PHP 7.1, MYSQL 5.6.38)

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#274]
Hey, Ich habe einen Fehler während der Installation von Lansuite auf meinem Webserver.
Und zwar nach Eingabe der Datenbank Daten bekomme ich folgenden Fehler:

```
Fatal error: Uncaught Error: Call to a member function get_tag_content() on null in /www/htdocs/w00c2db7/lansuite/modules/install/Classes/Install.php:254 Stack trace: #0 /www/htdocs/w00c2db7/lansuite/modules/install/Classes/Install.php(134): LanSuite\Module\Install\Install->InsertModules(NULL) #1 /www/htdocs/w00c2db7/lansuite/modules/install/Classes/Install.php(160): LanSuite\Module\Install\Install->WriteTableFromXMLFile('install') #2 /www/htdocs/w00c2db7/lansuite/modules/install/wizard.php(194): LanSuite\Module\Install\Install->CreateNewTables(0) #3 /www/htdocs/w00c2db7/lansuite/index_module.inc.php(55): include_once('/www/htdocs/w00...') #4 /www/htdocs/w00c2db7/lansuite/index.php(420): include_once('/www/htdocs/w00...') #5 {main} thrown in /www/htdocs/w00c2db7/lansuite/modules/install/Classes/Install.php on line 254
```

Da ich bei PHP nicht so fit bin, bin ich etwas ratlos. Vor allem kommt der fehler aber nur wenn ich die Datenbankinformationen richtig eingebe. Sobald ich den user mit root und als datenbankname lansuit eingebe geht er weiter, sagt aber natürlich das er keine Verbindung zur Datenbank hat was ja logisch ist. Die Chmod rechte habe ich wie in der Beschreibung gesetzt. Die Config file ebenso erstellt. Also was kann ich dagegen machen? Muss ich eine Lokale Installation mit diesem Docker machen?

Installationsfenster 1
![fraghouse](https://user-images.githubusercontent.com/39373552/40177765-c4fad9fc-59df-11e8-97e0-9c3448f54c4e.jpg)
Installationsfenster 2
![fraghouse2](https://user-images.githubusercontent.com/39373552/40177792-d7994d3c-59df-11e8-806f-d98f457704b3.jpg)
Jetzt erscheint der obige Fehler.

Bitte um Hilfe. Danke

**Comment by M4LuZ** [comment]
Moin, 
der Fehler wurde uns bereits hier gemeldet: #269 
Ist definitv ein Fehler im aktuellen Git Master, der wohl durch das refactoring hervorgerufen wurde.

**Comment by daencore** [comment]
Danke für die schnelle Antwort. Ja ist die Aktuelle Git Master. Auf gut deutsch einfach warten bis der Neue Release da ist und aktuell noch mit 4.2 Arbeiten oder?

**Comment by andygrunwald** [comment]
Ich werde heute Abend den Master fixen und wieder zum laufen bringen. Pinge
euch dann hier. Ok?

daencore <notifications@github.com> schrieb am Do. 17. Mai 2018 um 15:33:

**Comment by M4LuZ** [comment]
OK for me ;)
@daencore : mit LS 4.2 wirst du bei PHP 7.1 nicht glücklich.

Wir versuchen gerade ein neues Release fertig zu machen, Fortschritt ist in #224 zu sehen.
Ich erwarte aber durchaus, dass da noch ein paar Fehler durch das refactoring dazu gekommen sind, die wir jetzt noch ausbügeln müssen.

**Comment by daencore** [comment]
Hey, Danke dann kann ichs endlich mal Installieren. :-)

Habe leider immer auch noch das Problem wenn ich die 4.2 Installieren will das ich nur ne Weiße Seite zu sehen bekomme.

**Comment by daencore** [comment]
@M4LuZ Super danke. Dann warte ich noch. Gibts einen Groben Zeit überblick wann das in etwa sein wird?

Und ja bei der 4.2 bekomme ich diesen Ominösen White Screen zu sehen der schon im alten Forum Diskutiert wurde.

**Comment by M4LuZ** [comment]
"when it's done" ;)
Ne, würde mich da echt nicht aus dem Fenster lehnen.
Sobald wir aber die paar Fehler hier ausgebügelt sind, ist ja auch der Git Master erstmal i.O.

Wie gesagt: Mit LS 4.2 wirst du mit PHP 7.1 nicht glücklich.
Unter anderem wegen des WSOD ;)

**Comment by andygrunwald** [comment]
Ich hab einen Fix in #275 eingetütet.

**Comment by M4LuZ** [comment]
@daencore Versuch es bitte noch mal mit den neuen changes im Master und gib dann Feedback, ob es für dich sauber läuft

**Comment by daencore** [comment]
@M4LuZ Danke für den Schnellen einsatz. Habe ich soeben hochgeladen. Bekomme allerdings bereits nach dem ersten Aufruf jetzt folgenden Fehler:

```
Warning: require(/www/htdocs/w00c2db7/lansuite/vendor/autoload.php): failed to open stream: No such file or directory in /www/htdocs/w00c2db7/lansuite/index.php on line 3

Warning: require(/www/htdocs/w00c2db7/lansuite/vendor/autoload.php): failed to open stream: No such file or directory in /www/htdocs/w00c2db7/lansuite/index.php on line 3

Fatal error: require(): Failed opening required '/www/htdocs/w00c2db7/lansuite/vendor/autoload.php' (include_path='.:/usr/share/php:..') in /www/htdocs/w00c2db7/lansuite/index.php on line 3
```

**Comment by M4LuZ** [comment]
@daencore das sieht ganz hart danach aus, dass du die Abhängigkeiten nicht mit composer installiert hast.
Eigentlich sollte schon `install.php`sich schon über das fehlende Verzeichnis mokiert haben.
Hast du denn nur Webspace gemietet oder hast du einen (v)root mit shell access?

**Comment by daencore** [comment]
@M4LuZ Ja stimmt, hab nicht mitgedacht. Habs einfach auf den Webspace gezogen. Probiers gleich nochmal mit Docker und melde mich dann nochmal.

**Comment by daencore** [comment]
@M4LuZ Soeben probiert und Installiert. Lief alles Perfekt ohne Fehler! Vielen Dank euch! :-)
