### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#293]
Ich bekomme folgende Fehlermeldung wenn ich den aktuellen master brunch testen möchte

`Fatal error: Uncaught Error: Cannot access private property LanSuite\Module\Party\Party::$count in /www/htdocs/w01237f1/netsession.net/lansuite/modules/usrmgr/boxes/userdata.php:80 Stack trace: #0 /www/htdocs/w01237f1/netsession.net/lansuite/modules/boxes/boxes.php(84): include_once() #1 /www/htdocs/w01237f1/netsession.net/lansuite/index.php(410): include_once('/www/htdocs/w01...') #2 {main} thrown in /www/htdocs/w01237f1/netsession.net/lansuite/modules/usrmgr/boxes/userdata.php on line 80`

**Comment by M4LuZ** [comment]
Oh ja. Alle Attribute der Klasse `Party` werden an verschiedensten Stellen direkt verwendet.
Da ist @andygrunwald wohl was beim Refactoring durchgerutscht... ;)

**Comment by Pimmal** [comment]
Fixed, top.
