### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#295]
Ich weiß nicht obs bereits bekannt ist aber ich reporte mal alles was mir beim testen auffällt.

**http://test.netsession.net/?mod=guestlist&action=guestlist**
`Fatal error: Uncaught Error: Call to undefined function LanSuite\Module\Seating\Seat2() in /www/htdocs/w01237f1/netsession.net/lansuite/modules/guestlist/search.inc.php:6 Stack trace: #0 /www/htdocs/w01237f1/netsession.net/lansuite/modules/guestlist/guestlist.php(123): include_once() #1 /www/htdocs/w01237f1/netsession.net/lansuite/index_module.inc.php(84): include_once('/www/htdocs/w01...') #2 /www/htdocs/w01237f1/netsession.net/lansuite/index.php(419): include_once('/www/htdocs/w01...') #3 {main} thrown in /www/htdocs/w01237f1/netsession.net/lansuite/modules/guestlist/search.inc.php on line 6`

**http://test.netsession.net/?mod=server2**
`Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /www/htdocs/w01237f1/netsession.net/lansuite/ext_scripts/lgsl/lgsl_files/lgsl_class.php:130 Stack trace: #0 /www/htdocs/w01237f1/netsession.net/lansuite/ext_scripts/lgsl/lgsl_files/lgsl_class.php(308): lgsl_database() #1 /www/htdocs/w01237f1/netsession.net/lansuite/ext_scripts/lgsl/lgsl_files/lgsl_list.php(15): lgsl_query_group() #2 /www/htdocs/w01237f1/netsession.net/lansuite/ext_scripts/lgsl/index.php(34): require('/www/htdocs/w01...') #3 /www/htdocs/w01237f1/netsession.net/lansuite/modules/server2/show.php(7): require_once('/www/htdocs/w01...') #4 /www/htdocs/w01237f1/netsession.net/lansuite/index_module.inc.php(98): include_once('/www/htdocs/w01...') #5 /www/htdocs/w01237f1/netsession.net/lansuite/index.php(419): include_once('/www/htdocs/w01...') #6 {main} thrown in /www/htdocs/w01237f1/netsession.net/lansuite/ext_scripts/lgsl/lgsl_files/lgsl_class.php on line 130`

**http://test.netsession.net/index.php?mod=usrmgr&action=details&userid=1**
`Fatal error: Uncaught Error: Class 'LanSuite\masterform' not found in /www/htdocs/w01237f1/netsession.net/lansuite/inc/Classes/MasterComment.php:74 Stack trace: #0 /www/htdocs/w01237f1/netsession.net/lansuite/modules/usrmgr/details.php(406): LanSuite\MasterComment->__construct('User', '1') #1 /www/htdocs/w01237f1/netsession.net/lansuite/index_module.inc.php(90): include_once('/www/htdocs/w01...') #2 /www/htdocs/w01237f1/netsession.net/lansuite/index.php(419): include_once('/www/htdocs/w01...') #3 {main} thrown in /www/htdocs/w01237f1/netsession.net/lansuite/inc/Classes/MasterComment.php on line 74`

**Comment by M4LuZ** [comment]
Ne, immer her damit! 
Wir stecken zwischen refactoring und release-schnüren und sind aktuell definitv nicht auf einem stabilen & getesteten Stand.
Das zweite ist besonders interessant, da mit #277 gerade ein pull-request offen ist, um das server2-modul komplett zu entfernen.
Nutzt ihr das wirklich produktiv? 
Habt ihr die anscheinend im Moment vorhandenen Fehler gefixt und könnt entsprechenden Code zur Verfügung stellen?

**Comment by Pimmal** [comment]
1. Servermodul hatten wir schon teilweise benutzt, aber war glaub ich recht buggy also von daher kanns dann raus außer jemand tut sich aktualisieren an.

2. Nein wir haben nix gefixt, ich kanns mir ansehen aber ist hald noob PHP Kenntnisse, weiß ne dob du damit glücklich wirst.

**Comment by M4LuZ** [comment]
Das server2-Modul basiert auf dem LGSL-Framework, was seit 2014 nicht weiter entwickelt wird. Dementsprechend groß ist da der Sinn und die Chance, das auf PHP 7 zum laufen zu bekommen.
Für die restlichen Probleme (und einem ganzen Sack mehr) habe ich PR #296 geöffnet

**Comment by andygrunwald** [comment]
> Das zweite ist besonders interessant, da mit #277 gerade ein pull-request offen ist, um das server2-modul komplett zu entfernen.

Der Fehler resultiert, wenn man das Modul `server2` anschaltet und auf den Menü-Punkt drückt.
Es werden keine LanSuite DB Connection Daten an die Funktion übergeben.
Das kann so noch nie funktioniert haben. Deswegen ist der PR zum removal drin.
Es sieht so aus als hätte @Pimmal das Modul installiert um es auszuprobieren.

#296 wurde gerade gemerged. Vielen Dank fürs testen @Pimmal und fürs kümmern @M4LuZ!

**Comment by Pimmal** [comment]
Also fixed. Thx.
