### ISSUE TITLE
"Add new party" silently fails without error

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#297]
## Expected Behavior
Additional Party should be added to DB when form under Parties->Add (calls modules/party/edit.php) is sent. 

## Current Behavior

Sending the form ends in a success message, but party is not added. 

## Possible Solution

My suspicion is that the callback function added to MasterForm cannot be called.
`$mf->AdditionalDBUpdateFunction = 'UpdatePartyID';`

related code in MasterForm.php:
```php
if ($this->AdditionalDBUpdateFunction) {
   $addUpdSuccess = call_user_func($this->AdditionalDBUpdateFunction, $id);
 }
 if ($addUpdSuccess) {
     if ($this->isChange) {
         $func->confirmation(t('Die Daten wurden erfolgreich geändert.'), $_SESSION['mf_referrer'][$this->GetNumber()]);
       } else {
                 $func->confirmation(t('Die Daten wurden erfolgreich eingefügt.'), $this->LinkBack);
       }
}
```
What to do:
* Add check to MasterForm to check if provided callback functions can be executed
* Add check if execution of callback function was successful
* fix the underlying issue

## Steps to Reproduce (for bugs)

Try to add a new party

## Your Environment

* Version used: lansuite/HEAD
* Operating System and version:
* Enabled features:

**Comment by M4LuZ** [comment]
Having looked at this a bit more I suspect that the root issue is something else.
UpdatePartyID does not return a value, but is executed succesfully

**Comment by Pimmal** [comment]
"Add new party" silently fails without error => i have no problem on my test site, party creating works without problems.

**Comment by M4LuZ** [comment]
Interesting. This could be related to MariaDB then. If I confirm that, I'll close this here and merge this into the MariaDB compatibility ticket at #185

**Comment by Pimmal** [comment]
@M4LuZ i have now moved the site to my own hosting server were MariaDB is running, i can not see such problem. For me all is fine.
`MariaDB Version 10.1.26-MariaDB-0+deb9u1 gefunden`

**Comment by M4LuZ** [comment]
Interesting. Must be an issue with my test setup then.
Thanks a bunch for the feedback!

I'll close this then and re-open if we ever see the issue re-appear

**Comment by aj-gh** [comment]
Tested with both 10.1.37-MariaDB-0+deb9u1 and MySQL 5.6.43 - no issues creating a 2nd party.
Does this still occur?

**Comment by andygrunwald** [comment]
I created a Pull Request to fix this one. See https://github.com/lansuite/lansuite/pull/652
