### ISSUE TITLE
Seatmap without pictures

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#298]
No pictures are shown on the seat map
You can have a look here: http://test.netsession.net/index.php?mod=seating&action=show&step=2&blockid=1

**Comment by M4LuZ** [comment]
Your seatmap seems to contain no seats at all. 
Were you not able to add them, are they not displayed or is there a different issue?

**Comment by Pimmal** [comment]
I have added a block, all is ok during the creation process. But afterwards as you can see no seats are displayed,

**Comment by M4LuZ** [comment]
Just checked this with the current git master. This seems to be OK now (although LS does not return to the overview once you press safe on the seat definition).

Can you please check again and verify with the current git master?

**Comment by M4LuZ** [comment]
Closed as functionality seems OK and submitter did prove any objection in time
