### ISSUE TITLE
News link broken

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#299]
News created, news is shown on the news menu entrie.
If you are loged in and klick on the dashboard on these news then a error is occured.
This is the link from the news from dashboard: http://test.netsession.net/index.php?mod=news&action=comment&newsid=1&ms_page=0
`Fatal error: Uncaught Error: Class 'LanSuite\masterform' not found in /www/htdocs/w01237f1/netsession.net/lansuite/inc/Classes/MasterComment.php:74 Stack trace: #0 /www/htdocs/w01237f1/netsession.net/lansuite/modules/news/comment.php(55): LanSuite\MasterComment->__construct('news', '1', Array) #1 /www/htdocs/w01237f1/netsession.net/lansuite/index_module.inc.php(90): include_once('/www/htdocs/w01...') #2 /www/htdocs/w01237f1/netsession.net/lansuite/index.php(419): include_once('/www/htdocs/w01...') #3 {main} thrown in /www/htdocs/w01237f1/netsession.net/lansuite/inc/Classes/MasterComment.php on line 74`

**Comment by andygrunwald** [comment]
Aaaand #296 is merged. Can you test it again @Pimmal ?

**Comment by Pimmal** [comment]
solved
