### ISSUE TITLE
Drop support for PHP Version < PHP 7.0

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#3]
The PHP language is developing quite fast. Every version adds new features, deprecates and remove features that are insecure, not good practice or similar.

Right now the current maintained version is PHP 7.1. PHP 7.0 is supported and PHP 5.6 only receives security updates. See [PHP: Supported Versions](https://secure.php.net/supported-versions.php) for details.

Nearly every major shared hosting hoster has the opportunity to use PHP >= 7 right now.
Even all major Linux, BSD or Windows packages are updated.
LANSuite was developed some time ago and has still several lines of code only for backwards compatibility and support for older features. E.g.

* magic_quotes, open_basedir, etc.
* mysql extension

Even PHP 7.0 has features build in features that could make the work with this system more secure. E.g. working with proper return types.

## Suggestion

Drop official support for PHP versions below 7.0 and set PHP 7.0 as minimum requirement here.
This would 

a) slim the code base
b) offer us to modernize the code base

## How do we come to a conclusion to solve this ticket?

In my opinion this has to be a decision of the main contributors. I would encourage them to post their **+1 for drop support for PHP <= 5.6** or a **-1 for stay with the current state** here.

**Comment by M4LuZ** [comment]
No disagreement here.
We should just ensure first that we have full PHP 7.0 compatibility first ;)

**Comment by BenniGotchi** [comment]
In principle I would also agree here. But has anyone a clue, how to check the code base for compability with PHP 7.0 and up?
Or to put it the other way around. How to identify the code sections, that have to be updated?

**Comment by andygrunwald** [comment]
@BenniGotchi This is a good question, but i would see it from a different perspective.
I would not force to drop PHP support for version below 7.0. But if there is a function on the PHP docs that was introduced in PHP 7, we are free to use it.
Means: We don't cover PHP versions below 7.0 explicit and Lansuite might run on e.g. PHP 5.6. But we just don't accept bug reports with this kind of PHP versions.

I would start to setup a Webserver env with PHP 7.0 and activate the `error_reporting` to `E_ALL` incl. deprecated levels. If you then click through the site you will see a bunch of debug of E_DEPRECATED errors.
Of course, this will take time. But this is fine.

Another options would be to start the usage of static analyzer like [phan](https://github.com/etsy/phan).

**Comment by lxp** [comment]
We are also working towards PHP 7.0 compatibility and we agree to drop PHP < 7.0 support, so new code can already use all PHP 7.0 features.

**Comment by andygrunwald** [comment]
That is great to hear!

**Comment by M4LuZ** [comment]
I guess we can close this now?
(Given that  - in my understanding - we made the decision to move to PHP 7 while dropping backwards compatibility whenever we find a case that requires it?)

**Comment by andygrunwald** [comment]
> Given that - in my understanding - we made the decision to move to PHP 7 while dropping backwards compatibility whenever we find a case that requires it?

Under this circumstances, yes we can close it.

Final decision / tl;dr:

- Minimum supported PHP Version: 7.0
- LanSuite might work on PHP Versions lower than 7.0, but a) not tested b) no guarantee at all
- Code that is not necessary in PHP 7.0 anymore, can be removed
