### ISSUE TITLE
Party Map

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#301]
I dont know if it´s also a non used function but the Party Map is not displaying google maps.
http://test.netsession.net/index.php?mod=partylist&action=map
`Hoppla! Ein Fehler ist aufgetreten.
Google Maps wurde auf dieser Seite nicht richtig geladen. Technische Details dazu entnimmst du der JavaScript-Konsole.`

**Comment by M4LuZ** [comment]
Can confirm two issues found in the JS-console:
a)Module tries to load adress data even if nobody is registered for the party. This could be handled more gracefully, but should disappear when the first user registers.
b)Similar issue when the Google API key is not configured in the module. It still tries to load the map with an empty key.

So both problems should disappear once the requirements are met (users registered and API key entered), but this case could be handled more gracefully

**Comment by M4LuZ** [comment]
Opened pull-request #303 for this
