### ISSUE TITLE
Who is using LANSuite?

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#312]
Hey,

we the LANSuite-Team want to get in contact with the users who are using the LANSuite CMS.

If you are using LANSuite for your LAN Party, let us know.
We would love to know what

* you like
* you don't like
* you would improve and change

Furthermore, we would love to include you in our documentation as a user showcase.
If you agree to this, we would love to get your logo and your website.
Feel free to post it here :)

Andy

**Comment by Pimmal** [comment]
www.Netsession.net

Wir nutzen die Lansuite sind aber was das Template System angeht nicht so begeistert oder zu blöd eine vernünftiges Design hin zu bekommen.

Ebenfalls vermissen wir ein Swiss System bei den Turnieren.

**Comment by M4LuZ** [comment]
Quick Google for the news module header revealed:

## Active
https://gybralanre.de/index.php?mod=news&action=show&news_page=all
http://www.psycholanpartys.org/index.php?mod=news
https://www.netsession.net/index.php?mod=news&action=show&news_page=all
https://www.lansin.de/lansuite/index.php?mod=news
http://lan.hs-s.com/index.php?mod=news
https://lansuite.fhlan.info/index.php?mod=news&action=show&news_page=all
https://lan.stormclan.de/index.php?mod=news
http://odyssee.events/?mod=news
http://www.moinmoinlan.de/index.php?mod=news
https://synergy-lan.de/index.php?mod=news
https://my-trust.de/index.php?mod=news
http://www.party-at-lan.at/index.php?mod=news
https://www.zock-verein.de/index.php?mod=news
http://clansap.org/?mod=news
https://berg-lan.de/
http://www.ff-katharein.at/lansuite/index.php?box_action=change&boxid=10
https://zock-verein.de/index.php
http://www.e51partycrew.de/e51lan/
http://lan.erdbeermilch.de/index.php?box_action=change&boxid=6
http://www.rage-lan.de/index.php?box_action=change&boxid=5
http://www.ria-lan.de/index.php?mod=home
http://www.lan.wowstofftiere.de/
http://www.xtrlan.net/?mod=seating
http://www.party-at-lan.at/index.php?mod=seating
http://cs.rashia.de/

## Inactive
http://www.zockimknast.de/index.php?mod=news (seems inactive)
https://mittweida-lan.de/index.php?mod=news (seems inactive)
https://www.lansin.de/lansuite/index.php?set_party_id=3
https://my-trust.de/index.php?set_party_id=1
http://www.teamffd.de/
http://www.dreamlan.ch/
http://its-bischoff.de/index.php?set_party_id=2
http://www.riedls.net/?mod=home
http://www.esportsonline.de/?mod=seating
http://cup.rushoholics.de/
http://die-kabelsalat.de/?mod=home
http://www.alp-lan.com/?mod=home
http://lanparty-gammertingen.de/lansuite/index.php?set_party_id=2
http://www.laonda.dartdiddl.de/index.php
https://b6-lan.de/index.php?mod=seating
http://www.woh-lan.de/?mod=home

## Installed, but dead
http://www.szenelan.at/index.php

## Unable to check (webfilter...)
http://burschi-lan.de/index.php?mod=info2&action=show_info2&id=1
http://www.wc3bs.com/tourney/index.php?language=en&language=de
http://www.assassinslan.eu/index.php?mod=seating



I have to say I'm really quite impressed how any active parties there are running with this! 😲

**Comment by andygrunwald** [comment]
@Pimmal Was ist ein Swiss System bei den Turnieren? Das hier? https://de.wikipedia.org/wiki/Schweizer_System

@M4LuZ True. A lot of people using this.
Before we include a couple of them in our documentation as users i would love to get there approval  :)

**Comment by Pimmal** [comment]
@andygrunwald jup, hier die Beschreibung der ESL dort nutze ich das System aktiv.

> In jeder Runde, falls es eine ungerade Anzahl an Teilnehmern gibt, wird ein Freilos gegeben an:
In der ersten Runde: Falls der Cup geseeded wurde, erhält der höchste Seed das Freilos. Ansonsten wird das Freilos zufällig vergeben.
In den folgenden Runden: Wird ein zufälliger Teilnehmer aus der Gruppe mit der niedrigsten Sieg / Niederlagen-Wertung gewählt.
In der ersten Runde basiert die Paarungen auf dem Seeding (Top vs Low) oder ist komplett Zufällig.
In den folgenden Runden werden alle Teilnehmer anhand ihrer Sieg / Niederlagen-Wertung in Gruppen zusammen gefasst. Dabei beginnt die Gruppe mit der höchsten Sieg / Niederlagen-Wertung:
Bei einer ungeraden Gruppe wird ein zufälliger Teilnehmer einer Gruppe mit einem zufälligen Teilnehmer der nächsten Gruppe gepaart.
Verbleibende Teilnehmer werden zufällig mit einander gepaart.
Das Ranking basiert auf Siegen, Niederlagen und dann den Tiebreaker Punkten. Falls ein oder mehrere Teilnehmer auch mit Tiebreaker Punkten auf dem selben Platz sind, bleibt das auch so, außer es wurde in den Regeln eine weitere Tiebreaker Regel hinterlegt!
Sonderfälle:
Im Allgemeinen sollten die selben Teilnehmer nicht mehrmals auf einander Treffen wenn vermeidbar: Falls es nicht vermeidbar ist, werden Teilnehmer mit einander gepaart die bisher noch nicht so oft gegeneinander gespielt haben.
Im Allgemeinen werden Teilnehmer nicht mehrfach mit Teilnehmern einer höheren oder niedrigeren Gruppe gepaart : Falls up/downgrading dennoch nötig ist, wird der Teilnehmer genommen, wer bisher am wenigsten außerhalb seiner eigentlichen Gruppe gepaart wurde.

**Comment by Pimmal** [comment]
@andygrunwald bisher haben wir uns mit https://challonge.com/ beholfen, wäre hald toll das auf der Seite selbst zu haben.
Hier ein Link zu nem Swiss Beispiel:
https://challonge.com/de/Swiss_System

**Comment by andygrunwald** [comment]
@SoundHunter Das klingt nach einer Uni oder etwas ähnlichem? Dürften wir dies in der Dokumentation als Nutzer nennen?

Das Tournament-Modul ist einer der wichtigsten Module. Wenn eine neue Version von LanSuite ready ist, werden wir wohl etwas daran arbeiten.
Feedback von euren Turnierleitern wäre sehr willkommen.

**Comment by daencore** [comment]
Hey, Also Wir von den Infernal Chicken Hunters Veranstalten jedes Jahr die Fraghouse Lan mit 200 Teilnehmer. Wir nutzen bisher eine Alte Version von Lansuite und haben diese wegen der DSGVO offline genommen und Warten Aktuell auf einen neuen Release von euch damit wir für unsere LAN 2019 wieder einen Ordentlichen Webauftritt haben. Unsere Homepage findet ihr auf [www.fraghouse.at](url)
Danke für Eurer bemühen das Ihr dieses Projekt weiter voran treibt! Die LAN Szene lebt!

**Comment by maxmarkus** [comment]
Super cool that you're on github (well, haven't looked for lansuite since 4.2 in year 2016 or so..) www.headshot.at in St. Johann in Tirol .. 46th Lan upcoming

**Comment by hnxfirefly** [comment]
We from Haag-networX are using Lansuite too. It's also a 200 Gamers lan. https://www.hnx.at
But we are using a fork from it with a new Password hash and an edited Session handling to support easy singlesignon for phpbb3

**Comment by JDLPIXEL** [comment]
Die Registrierung eines neuen Accounts bei **Berg-Lan.de** funktioniert bei euch anscheinend nicht.
Wollte nur eben Bescheid geben.

**Comment by andygrunwald** [comment]
@JDLPIXEL Was meinst du genau? Wir sind nicht für die Registrierung bei Berg-Lan.de zuständig. Bitte kontaktiere das Berg-Lan.de-Team selbst. Dies ist nur die Software, die auf Berg-Lan.de genutzt wird.

**Comment by M4LuZ** [comment]
Also während der Ort natürlich nicht ganz passt ist der Hinweis elementar und extrem nützlich, da zumindest unsere Installation zwei Fehler schmeisst, die LANsuite-generisch sein könnten.

Ich mach mal ein separates Ticket auf und informiere @JDLPIXEL sobald es wieder läuft

**Comment by andygrunwald** [comment]
Hey all - Thanks for the feedback.
I take it seriously and created own tickets to work on:

- https://github.com/lansuite/lansuite/issues/1045
- https://github.com/lansuite/lansuite/issues/1047
- https://github.com/lansuite/lansuite/issues/1046

I also created https://github.com/lansuite/lansuite/pull/1048 to list users of LanSuite.

**Comment by andygrunwald** [comment]
@Pimmal @SoundHunter @daencore @maxmarkus @aj-gh @hnxfirefly @JDLPIXEL LANSuite hat nun eine Discord Community unter https://discord.gg/3wkDqGmrFZ - Vielleicht wollt ihr ja auch mal dort vorbei schauen?

Wir freuen uns auf euer Feedback!

**Comment by maxmarkus** [comment]
Danke für die gute Zeit mit dem lansuite Lansystem (2013-2023)! Wir sind mit der [headshot.at](https://www.headshot.at) Anfang des Jahres zu [KLMS](https://github.com/KRRUg/KLMS) gewechselt, da wir nur Anmeldung, Sitzplan und ~nicht mal~ Turniere brauchen. Im Discord schau ich dennoch vorbei 👍
