### ISSUE TITLE
Fragen zur aktuellen Master Branch

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#339]
Hallo, habe es geschafft die Aktuelle Master Brunch endlich fehlerfrei zum laufen zu bringen. Jetzt sind aber ein paar Fragen aufgetaucht.

1. Welche Dateien werden wirklich noch benötigt für den Betrieb der Seite und was kann man alles Löschen im Verzeichnis der Master? Es befinden Sich ja nach wie vor einige Docker Dateien, .md usw. im Verzeichnis. Darüber habe ich leider nichts gefunden. Hier mein Verzeichnis:
![bild 1sds](https://user-images.githubusercontent.com/39373552/44617097-5f5aa100-a85d-11e8-9547-0ff77598539f.jpg)

2. Wenn eine Neue Version (Master oder Release) erscheint wie ist die dann upzudaten? Gibts da dann was zu beachten oder sind die Dateien im Verzeichnis einfach zu überschreiben? Ich weiß das ihr geplant habt dies mal ordentlich zu dokumentieren aber das wird vmtl. noch dauern. (https://lansuite.github.io/lansuite/docs/upgrade.html)

Danke für Eure Infos. Und Sorry für die Anfängerfragen. :-)

**Comment by daencore** [comment]
Eine Weitere Frage ist aufgetaucht. Besteht die Möglichkeit in den WYSIWYG Editor Google Fonts einzubinden? Da wir auf der Seite eine Andere Schriftart benutzen passen die Geschriebenen Texte sonst nicht wirklich zusammen. Ich habe ein paar Sachen dazu im Netz gefunden über die Einbindung in den FCKeditor. Jedoch hab ich es nicht geschafft diese schriften auch wirklich einzubauen. Habt Ihr eine Idee/Lösung wie man das umsetzen könnte?

**Comment by M4LuZ** [comment]
Moin, ich arbeite mich mal von oben durch:

> Hallo, habe es geschafft die Aktuelle Master Brunch endlich fehlerfrei zum laufen zu bringen.

Das klingt so, als ob das selbst mit Anleitung nicht so einfach war. 
Kannst du uns bitte Rückmeldung geben, ob und was nicht so gut beschrieben war und wo du hingst?

> Welche Dateien werden wirklich noch benötigt für den Betrieb der Seite und was kann man alles Löschen im Verzeichnis der Master?

Meine Empfehlung ist, einfach alles so zu lassen, wie es ist. 
Die zusätzlichen Dateien tun nicht weh (weder vom Platz noch von der Sicherheit), tauchen beim nächsten Update sowieso wieder auf und so vermeidet man doch eine Datei zu erwischen, die man lieber behalten hätte.

> Wenn eine Neue Version (Master oder Release) erscheint wie ist die dann upzudaten? Gibts da dann was zu beachten oder sind die Dateien im Verzeichnis einfach zu überschreiben? 

Kommt darauf an, ob du den Git-master mit Git nutzt, diesen nur einmalig rauskopiert hast oder ein Release verwenden willst:
* Git-master mit Git
  * `git pull`
  * Noch mal über die Doku gucken, ob etwas per Hand nachgezogen werden muss.
  * Fertig
* Einmaliges Checkout vom Git Master
  * Neue Version an die Seite legen
  * Bestehende Dateien kopieren
    * `config.php`
    * Design (falls eigenes)
    * Geänderte Dateien aus `ext_inc` übernehmen ( Gallery, Tournament icons, etc)
    * Noch mal über die Doku gucken, ob etwas per Hand nachgezogen werden muss.

* Release
  * Wenn du Glück hast, werden wir hierfür ein Auto-Update stellen, ansonsten analog zum letzten Fall

> Besteht die Möglichkeit in den WYSIWYG Editor Google Fonts einzubinden?

Ich würde dich jetzt gerne auf die alte LanSuite-Doku verweisen, nur leider wurde die Seite vom Netz genommen.
Generell kannst du die Schriftarten über die Variabe `FCKConfig.FontNames` in `fckconfig.js` anpassen.
Aber natürlich muss der Client die entsprechende Schrift ebenfalls installiert haben oder diese muss auch noch von der Webseite zur Verfügung gestellt werden. Siehe z.b. : https://stackoverflow.com/questions/2237540/how-do-i-load-external-fonts-into-an-html-document

**Comment by daencore** [comment]
@M4LuZ Danke für die Rückmeldung.

> Das klingt so, als ob das selbst mit Anleitung nicht so einfach war.
Kannst du uns bitte Rückmeldung geben, ob und was nicht so gut beschrieben war und wo du hingst?

Nun eure Beschreibung passt grundsätzlich so weit ganz gut. Ich hatte ein Problem mit Docker selbst. Und zwar bekam ich beim befehl docker-compose up nur eine Fehlermeldung. Nach einigen Tutorials und Suche hab ich das Problem dann gefunden. Im Prinzip musste ich Docker komplett zurücksetzen und dann ging es. Allerdings Für Anfänger und reinen Windows Nutzer am Anfang etwas Schwierig das Ganze da eure Beschreibung für Linux sein dürfte und somit nicht alle Befehle so Funktionieren. Mit ein Bisschen Google Hilfe hab ich auch das hinbekommen.

> Meine Empfehlung ist, einfach alles so zu lassen, wie es ist.
Die zusätzlichen Dateien tun nicht weh (weder vom Platz noch von der Sicherheit), tauchen beim nächsten Update sowieso wieder auf und so vermeidet man doch eine Datei zu erwischen, die man lieber behalten hätte.

Ist OK. Dachte eigentlich nur zwecks der Übersicht.

> Kommt darauf an, ob du den Git-master mit Git nutzt, diesen nur einmalig rauskopiert hast oder ein Release verwenden willst. Einfach nur reinkopieren ist nicht die beste Idee, da Dateilöschungen damit nicht übernommen werden.

Ähm ja. Ich habe die Git-Master runter geladen da diese ja die Aktuellste Version für das Neue PHP ist. Diese dann unter Windows mit Docker Installiert (docker-compose run php composer install). Das Ergebnis davon hab ich dann auf meinen Webspace gepackt, chmod gesetzt und dort dann mit der install.php Fertig Installiert. Funktionierte eigentlich fehlerfrei! Nur eben jetzt der Fehler aus #340 

> Ich würde dich jetzt gerne auf die alte LanSuite-Doku verweisen, nur leider wurde die Seite vom Netz genommen.

Das Probiere ich demnächst mal und gebe dann Rückmeldung ob ich es geschafft habe. Danke bisweilen für die Infos und Tipps.

**Comment by andygrunwald** [comment]
Hey,

also eine Installations-Anweisung ohne Docker müssen wir noch schreiben. Wenn du uns helfen möchtest, wäres es toll, wenn du ein Issue hier erstellen würdest mit den Schritten, die du dafür gemacht hast. Denn so wie ich dich verstanden habe, läuft deine Installation nun :)

Wegen dem Dateien löschen:
Da stimme ich @M4LuZ zu. Wenn du diese Dateien nicht zugänglich machen möchtest, würde ich dir empfehlen, das ganze über deine Webserver-Konfiguration (zB htaccess) zu verbieten.

Wegen dem Update:
Auch das müssen wir noch dokumentieren. Gerne kannst du hier auch ein eigenes Issue erstellen und zB die kleine Anleitung von @M4LuZ übernehmen. Dann bekommen wir ggf. eine Anleitung zusammen :)

Wegen der Schriftart:
Ich hatte bei meiner Installation ebenfalls Custom-Fonts (im PDF-Modul).
Kannst du hier auch ein Ticket erstellen, damit wir diese supporten?
Weil das Problem ist, wenn du JS-Dateien von LanSuite editierst, werden diese bei jedem update überschrieben. Und das Problem tritt immer wieder auf.

**Comment by daencore** [comment]
> also eine Installations-Anweisung ohne Docker müssen wir noch schreiben. Wenn du uns helfen möchtest, wäres es toll, wenn du ein Issue hier erstellen würdest mit den Schritten, die du dafür gemacht hast. Denn so wie ich dich verstanden habe, läuft deine Installation nun :)

Ja die Installation Läuft. Hier nochmal meine Schritte die ich unternommen habe.

- Docker Community Edition für Windows Installiert.
- Die Aktuelle Master als Zip herunter geladen und in einen Ordner gepackt.
- Die config.php manuel erstellt mit dem Inhalt aus eurer Beschreibung und mit meinen Daten ausgefüllt.
- PowerShell gestartet (Windows 10) und zum Pfad des Ordners geleitet (cd pfad)
- Datei und Ordnerberechtigung (Chmod 777) gesetzt mit `ICACLS "Pfad" /grant:r "Benutzer:(F)" /C`
- docker-compose up
- docker-compose run php composer install
- Powershell geschlossen und den Ordnerinhalt auf meinen FTP gezogen. Chmod dort nochmals gesetzt mit 777 für die config.php und ext_inc und die Install.php im Browser ausgeführt. Setup gefolgt und lauft.

> Wegen der Schriftart:

Nun habe das relativ Simpel gelöst, ist aber wie du schreibst keine schöne Lösung da beim nächsten Update das überschrieben wird.
Ich hab einfach die Googlefont in den Head bei `Design/MeinDesign/templates/main.htm` eingebettet. 
`<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">`

Und in der CSS dann die schriftart geändert `font-family: 'Roboto' , sans-serif;`

Und um diese dann in den Editor zu bringen musste ich eben in der besagte Datei `fckconfig.js` die schrift einfügen `FCKConfig.FontNames		= 'Roboto;Arial;Comic Sans MS;Courier New;Tahoma;Times New Roman;Verdana' ;`
Funktioniert Perfekt.

**Comment by daencore** [comment]
Gibt es künftig mal ein Update für den FCK WYSIWYG Editor? Weil dieser Spinnt mit Google Chrome. Im Firefox und IE habe ich keine Probleme und wird alles korrekt angezeigt. Getestet auf 2 Verschiedenen PCs.
Im Chrome bleibt der einfach ohne Inhalt Und auch die Bearbeitungszeile mit der Schriftart fehlt: 
![bild 1df](https://user-images.githubusercontent.com/39373552/44992401-64bf9600-af97-11e8-9058-1a9795bfe14f.jpg)

**Comment by andygrunwald** [comment]
Danke für die Schritte! Dies hilft uns bei der Anleitung.

> Gibt es künftig mal ein Update für den FCK WYSIWYG Editor?
Darüber habe ich auch mal nachgedacht. Der FCK Editior bietet eine neue Version. Die Integration ist jedoch deutlich anders als in der vorhanden Version.
Benötigt somit etwas Zeit.

**Comment by daencore** [comment]
Hallo Zusammen

Ich habe noch ein Problem entdeckt.

Wir nutzen ein LetsEncrypt HTTPS Zertifikat das erzwungen wird. Evtl. liegts daran.
Wenn man das Passwort zurücksetzen will bekommt man einen Link in der Mail der nicht Funktioniert da er hinter die Domain einen SSL 443 Port anhängt. Sieht dann so aus in der Mail: `http://meinedomain.at:443/index.php?mod=usermgr&action=pwrecover&step=3&fcode=.....`

Wenn man auf den link klickt kommt natürlich folgende Meldung:
`Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.`

Irgend eine Idee? Bitte um Hilfe. Danke

**Comment by M4LuZ** [comment]
Moin,

das ist interessant, das Problem habe ich 2015 schon behoben. Scheinbar ist das eine der Änderungen, die nie wieder zurück geflossen ist. Die Registrierungs-Email ist AFAIK ebenfalls betroffen.

**Comment by daencore** [comment]
@M4LuZ 
> das ist interessant, das Problem habe ich 2015 schon behoben. Scheinbar ist das eine der Änderungen, die nie wieder zurück geflossen ist. Die Registrierungs-Email ist AFAIK ebenfalls betroffen.

Jep die Registrierung ist auch betroffen. Es ist Egal ob es HTTP oder HTTPS link ist. Dieser wird automatisch übernommen. Jedoch der angehängte Port macht dieses Problem. Wie bekommt man den Wieder raus aus dem Link?

**Comment by andygrunwald** [comment]
@M4LuZ 

> das ist interessant, das Problem habe ich 2015 schon behoben. Scheinbar ist das eine der Änderungen, die nie wieder zurück geflossen ist. Die Registrierungs-Email ist AFAIK ebenfalls betroffen.

Kannst du dafür einen Pull Request erstellen?

**Comment by daencore** [comment]
@M4LuZ 
Funktioniert Perfekt. Vielen Dank :-)
