### ISSUE TITLE
PHP Warning bei Party Anmeldung

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#340]
Bekomme leider bei der Aktuellen Master einen Fehler wenn man sich zur Party anmeldet. Der Benutzer ist dann zwar zur Party angemeldet jedoch taucht dieser zb. nicht in der Gästeliste auf und wird auch Nicht in der Anmelde-Status Box angezeigt.

Edit: Wir verwenden Aktuell PHP 7.1 am Webserver. 

`PHP Warning: call_user_func() expects parameter 1 to be a valid callback, function 'ChangeAllowed' not found or invalid function name in /www/htdocs/w00c2db7/lansuite/inc/Classes/MasterForm.php on line 1071`

![bild 2ff](https://user-images.githubusercontent.com/39373552/44617432-67690f80-a862-11e8-92e5-bbb4a0f54356.jpg)

Bitte um Hilfe. Danke

**Comment by andygrunwald** [comment]
Ich habe dazu mal einen Fix in #341 vorbereitet.
