### ISSUE TITLE
Adminuser is not part of the "Signed up" list for a party

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#342]
## Expected Behavior

Adminuser is part of the signed up list for a party

## Current Behavior

> Desweiteren habe ich noch das Problem das der Adminaccount mit Nr. 0001 wenn er zur Party Angemeldet wird nicht im Anmelde Status und auch nicht in der Gästeliste auftauchen. Alle anderen Neu Registrierten Accounts werden korrekt angezeigt. Die Fehlermeldung erhält allerdings jeder der sich zur Party anmeldet.

## Context

This issue was reported by @daencore in https://github.com/lansuite/lansuite/pull/341#issuecomment-417794404

## Your Environment

* Version used: master (rev. ef4be80)

**Comment by BenniGotchi** [comment]
Sure, that The expected bahavior ist really expected?
For my understanding the guestlist should only Show  physical persons, that will attend the Party.
The Admin Account ist not really a physical Person.

For me that looks like an intended behavior.

**Comment by andygrunwald** [comment]
Up for discussion. You have a valid point.
I need to check this in detail. I raised this as a ticket because it was mentioned in #340 to don't forget it.

**Comment by M4LuZ** [comment]
It's not a bug, it is a feature:
![grafik](https://user-images.githubusercontent.com/13054177/44985802-e6a4c480-af81-11e8-9259-f941e0d949f7.png)

Orgas are not shown or counted by default unless this option is changed.

**Comment by daencore** [comment]
@M4LuZ 

This solve the Problem. Thank you!

**Comment by andygrunwald** [comment]
Even better! Thanks :)
