### ISSUE TITLE
Setting Language to English Breaks Website

### ISSUE THREAD

**Issue by TheDeadCPU** [lansuite/lansuite#344]
Hi, so after succesfully installing, I opened up the website, and changed the language from German to English, this made the website stop functioning, and throwing a lot of PHP errors.

Here's a imgur gallery with the php errors.
https://imgur.com/a/mUMN4RD

## Expected Behavior

Changing language to English should change language to English

## Current Behavior

Selecting English breaks the website.

## Steps to Reproduce (for bugs)

1. Start fresh server
2. On setup page change to english and hit apply.

## Your Environment

* Version used: Latest
* Operating System and version: Ubuntu Server 18.04 
* Docker Version: 18.06.1-CE
* Docker Compose Version: 1.22.0

**Comment by M4LuZ** [comment]
Looks like your translations are not loaded and it fails to translate the error message that it cannot translate the error message. Ending in a recursive loop of no return.

Is this a fresh installation? Seems the install wizard is loaded.

**Comment by TheDeadCPU** [comment]
I am indeed using a completely fresh docker installation. 
The server has been setup virtually, docker-ce installed, and docker-compose. 
Then used the steps over at https://lansuite.github.io/lansuite/docs/installation.html

**Comment by TheDeadCPU** [comment]
As a workaround, I set the site up using german language, using google translate works well for those that can't work their way around the german.
Afterwards setting the language to english does work. (even though there's quite a lot of stuff not translated, but this can be done manually)
