### ISSUE TITLE
Platzierung Stimmen bei Single-Elimination nach Abschluss eines Turnieres nicht. Bug?

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#349]
Und hier noch ein Bug.

Wir haben ein Turnier mit Single Elimination generiert. 
![turnierbaum](https://user-images.githubusercontent.com/39373552/45212896-5ffc2a00-b296-11e8-9691-fec85704d02c.jpg)

Im finale Spielen die 2 Gewinner aus der ersten Runde Gegeneinander, soweit alles Korrekt. Jedoch beim Spiel um Platz 2 Spielen die Beiden Verlierer gegeneinander aber das ist falsch. Diese sollten ja um Platz 3 Spielen. So wird beim Endergebnis der 2t Platzierte auf Platz 3 Verwiesen und der 3t Platzierte auf Platz 2.
![plazierung](https://user-images.githubusercontent.com/39373552/45213019-a81b4c80-b296-11e8-9155-53bfbcf491be.jpg)

Kann also nur ein Bug sein oder?

**Comment by M4LuZ** [comment]
Ich meine das ist mit folgendem Commit gefixt worden: 
https://github.com/M4LuZ/lansuite/commit/8af729f849fd19eadb512d1c17020662f57ae9d3
War auch im Bugtracker http://lansuite.orgapage.de//index.php?mod=bugtracker&bugid=1097&ms_page=0
Kann man aber leider die Details nicht nachgucken, da #239

**Comment by daencore** [comment]
@M4LuZ habe deinen Code übernommen und Funktioniert Wunderbar. Plätze werden jetzt Richtig angezeigt.

**Comment by daencore** [comment]
Ein Weiteres Problem habe ich noch mit dem Grafischen Turnierbaum. Dieser Wird nur in einem Kleinen Schmalen Fenster gezeigt zum Scrollen und mit Banner was ja total unnötig ist. Ist das ein weiterer Bug in der Aktuellen Master oder hab ich hier beim Design was verhaut?

Sieht dann immer so aus wenn man den Turnierbaum öffnet, immer die Gleichen Maße:
![bild 5](https://user-images.githubusercontent.com/39373552/45240885-86e44b80-b2ea-11e8-8645-f2b8887f7e2b.jpg)
Wenn man Runter scrollt kommt der Turnierbaum:
![bild 6](https://user-images.githubusercontent.com/39373552/45240891-89df3c00-b2ea-11e8-8527-ae545a788e04.jpg)

**Comment by M4LuZ** [comment]
>  hab ich hier beim Design was verhaut?

^this ;)

![grafik](https://user-images.githubusercontent.com/13054177/45241509-10951880-b2ed-11e8-83a1-123f51bd9d67.png)

**Comment by daencore** [comment]
@M4LuZ ja so sollte es aussehen. In welcher Datei definiere ich das das der Banner Verschwindet?

**Comment by M4LuZ** [comment]
Hi, kann ich dir ehrlich gesagt selber nicht sagen.
Müsste dazu in der alten doku gucken, kann ich aber nicht mehr :/

Taucht das in den standard-templates denn ebenfalls auf?
Ansonsten würde ich scharf mutmaßen, dass das _irgendwo_ durch eine Anpassung des templates, dass für jede Seite benutzt wird, reingekommen ist. 
Da der Baum in einem iFrame geladen wird, ist das eine eigene Seite (mit eigenem Header - sofern definiert)

**Ich mach das hier mal dicht, da das Ursprungsproblem gelöst ist.**
Wenn du nicht weiterkommst, dann mach bitte dafür ein neues Issue auf
