### ISSUE TITLE
Modul Titel lässt sich nicht ändern.

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#365]
Hey, Habe wieder ein Problem/Bug entdeckt.

Wollten den Titel von Board auf Forum ändern unter `Board/Mod-Konfig/Menü/Titel`. Dann kommt kurz eine Meldung in grün die man jedoch nicht lesen kann da der Browser sofort aktualisiert. Der Name bleibt bei Board und wird nicht geändert.
Folgendes steht im Log:
![bild 1hgm](https://user-images.githubusercontent.com/39373552/45571347-3464db00-b866-11e8-896a-64372086eb9d.png)

Auch bei jedem anderen Modul ist derselbe Fehler. Eine Idee woran das liegen könnte. Bitte um Hilfe. Danke

**Comment by aj-gh** [comment]
Und das sollte es auch bei dir beheben: https://github.com/lansuite/lansuite/pull/391

**Comment by aj-gh** [comment]
Sollte somit behoben sein..

**Comment by andygrunwald** [comment]
Danke dir, @aj-gh!
