### ISSUE TITLE
SQL Fail @ /index.php?mod=install&action=wizard&step=9

### ISSUE THREAD

**Issue by mbraun81** [lansuite/lansuite#367]
> Fehler:
> SQL-Failure. Database respondet: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
>
>Query: 
>CREATE TABLE IF NOT EXISTS ls_ip_blacklist (ip varbinary(16) NULL , module char(20) NOT NULL default '' , PRIMARY KEY (ip) ) ENGINE = MyISAM CHARACTER SET utf8
>SQL-Failure. Database respondet: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
>
>Query: 
>CREATE TABLE IF NOT EXISTS ls_ip_locklist (ip varbinary(16) NULL , module char(20) NOT NULL default '' , PRIMARY KEY (ip) ) ENGINE = MyISAM CHARACTER SET utf8

## Expected Behavior
Keine SQL-Fehler ;)
## Current Behavior
SQL-Fehler
## Possible Solution
All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
## Steps to Reproduce (for bugs)
* Neue Subdomain erstellt für einen Test.
* Git Clone, Abhängigkeiten(Composer) und DB (+User) über Plesk Onyx installiert und angelegt.
* Installations Wizard gestartet.
* Nach Admin Erstellung bei der Modul-Auswahl oben auf weiter geklickt und wieder zur Admin Erstellung gelangt. Erneute Modul-Auswahl nun unten auf weiter geklickt -> Fehler Meldung
## Your Environment
PHP: 7.0.32-0ubuntu0.16.04.1 FPM/FastCGI
MySQL: 5.7.23-0ubuntu0.16.04.1

**Comment by M4LuZ** [comment]
I'm quite sure this is related to incompatibilities also observed in #185 in regard to current MariaDB-versions
My suggestion so far would be to downgrade to MySQL 5.6 for the time being, otherwise try to modify the default DB scripts according to the message
