### ISSUE TITLE
New Entrys not highlightes

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#369]
## Expected Behavior

Usually LanSuite highlights new, unread eleements (System messages, Board Entrys etc) on the Dashboard / Start page

## Current Behavior

Highligting of unread elements is not working

## Possible Solution

No idea, please help me :o

## Steps to Reproduce (for bugs)

https://gyralanre.de
Every item that is new to you and your browser should be highlighted. It always was. Now if you click the link you will see that it is not.

## Context

Keeping overview of what has been recently added is severely compromised

## Your Environment

* Version used: newest, freshly pulled <one week ago
* Operating System and version: folloows, some Linux Core server
* Enabled features: Picture Gallery, Board, Clanmanager, Guest List, Info, Mail, Messenger, News, Party Managent, Seating, Sponsorss, Statistics, Tournaments, About, Logon, User Manager, Boxes, Cronjob, Installation, MasterSearch, Start Page

**Comment by HtHNightwolf** [comment]
I just found out that the highlighting was always done my orange glowing orbs in front of new, unread items. These still work inside the board. If it is read, then the orb is grey.
These orbs used to be (smaller but very much working) on the start page. They are gone completely in my case it seems. The big orbs within the board itself seem to be different picture files / objects since they are there and work.

**Comment by M4LuZ** [comment]
First of all I got mixed feelings about what you seem to do:
As you may note based on the 40 (and still increasing) open issues, the current Git Master is nowhere close to being ready to be used for productive use. 
The farther you move away from the old 4.2 release, the more issues you will see.
Personal recommendation would be to jump back to the state pre-refactoring that already has the PHP7 changes, use it with PHP 7.0 and MySQL 5.6 and maybe cherry-pick some of the corrections after that and be happy with that for the moment.
But on the other hand I cannot appreciate enough the viable feedback about the issues you encounter with the current Git Master.

In regard to your issue: 
I take from what you said that the grey/yellow orbs in front of the entries on the overview page are not shown.
That basically boils down to the style classes `DotRow`and `DotRowActive` not being applied correctly.
CSS is by far not my style, but I'll have a look

**Comment by M4LuZ** [comment]
I noted a difference between the Style definition of LS 4.2 and the version in the Git Master.
Base64 Encoded variant of DotRow in LS 4.2:

`data:image/gif;base64,R0lGODlhDAANANUAAPv7+/r6+vn5+ff39/b29vX19fPz8/Dw8O/v7+7u7u3t7ezs7Onp6ejo6Ofn5+bm5uTk5OPj4+Hh4eDg4N/f397e3tzc3Nvb29ra2tnZ2dbW1tXV1dPT09LS0tHR0c3NzcjIyMfHx8bGxsXFxby8vLe3t7W1tbOzs62traurq6mpqaioqKenp6ampqWlpaOjo6KioqGhoaCgoJ+fn5qampmZmf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAUUADYALAAAAAAMAA0AAAZxQJtwSCyGYrVaLEQswGYWAOAygxWELxaFwCVUWi/bRyZaJM5nUezjInkcjHi8U2rVNhmJY++QZDg0NBgTExEPhxJ+NCogDY6PjiMqGisLCJeYDTIaNikmCgOhAwgnKUICKCsdBgYdMSgCRBgogSgZQ0EAOw==`

And in the master:

`data:image/gif;base64,R0lGODlhDAANANUAAPv7+/r6+vn5+ff39/b29vX19fPz8/Dw8O/v7+7u7u3t7ezs7Onp6ejo6Ofn5+bm5uTk5OPj4+Hh4eDg4N/f397e3tzc3Nvb29ra2tnZ2dbW1tXV1dPT09LS0tHR0c3NzcjIyMfHx8bGxsXFxby8vLe3t7W1tbOzs62traurq6mpqaioqKenp6ampqWlpaOjo6KioqGhoaCgoJ+fn5qampmZmf//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAUUADYALAAAAAAMAA0AAAZxQJtwSCyGYrVaLEQswGYWAOAygxWELxaFwCVUWi/bRyZaJM5nUezjInkcjHi8U2rVNhmJY++QZDg0NBgTExEPhxJ+NCogDY6PjiMqGisLCJeYDTIaNikmCgOhAwgnKUICKCsdBgYdMSgCRBgogSgZQ0EAOw==`

If you have a keen eye (or use a diff tool) then you see that there is a slash missing.
Icons reappear if you add that.
Will now do a diff if also other icons are affected
