### ISSUE TITLE
Sitzplatzverwaltung: Anzeigefehler beim Überschreiben von Reservierung

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#373]
Fehler beim Zuweisen von Sitzplätzen in der Sitzplatzverwaltung:

## Expected Behavior

Fehlerfreie Anzeige bei der Rückfrage zum Überschreiben von Vormerkungen (keinem festen Sitzplatz)

## Current Behavior

        Auswahl: Dieser Sitzplatz ist noch frei (bzw. nur markiert)HTML_NEWLINESoll er fest reserviert oder nur markiert werden?
        Sitzplatz für TEILNEHMER reservieren(Ein evtl. zuvor für diesen Benutzer reservierter Platz wird freigegeben)
        Sitzplatz für TEILNEHMER markierenHTML_NEWLINE(Alle markierten Sitzplätze von AvX.iB34ST werden gelöscht, da TEILNEHMER noch nicht bezahlt hat)

## Possible Solution

HTML_NEWLINE richtig interpretieren

## Steps to Reproduce (for bugs)

1. Sitzplan
2. Platzverwaltung
3. User auswählen
4. Sitzbereich auswählen
5. einen bereits reservierten (gelben) Sitzplatz auswählen

## Context

see above

## Your Environment

neueste LanSuite

**Comment by HtHNightwolf** [comment]
okay, I fixed that one myself by deleting the NewLine. Still exists though.

**Comment by HtHNightwolf** [comment]
Use <br> instead.


... wenn mal einer reagiern würden. Ich schau mal ob ich raffe, wie ich hier was einchecke ...

**Comment by andygrunwald** [comment]
Hey @HtHNightwolf,
sorry für die späte Response. Privat habe ich gerade recht viel um die Ohren. Deswegen bleibt da recht wenig Zeit für die Open Source Arbeit an LanSuite über. Dafür bitte ich um Verständnis.

Um den Umgang mit Git/Github zu lernen empfehle ich https://try.github.io/.
Dort findest du Learning by Doing-Tutorials, die i.d.R. alle im Browser gemacht werden können.
Wenn du schon familär mit Git bist und nur Github fremd ist, schau doch mal in doe Dokumentation [Collaborating with issues and pull requests](https://help.github.com/categories/collaborating-with-issues-and-pull-requests/). Speziell das Chapter [Creating a pull request
](https://help.github.com/articles/creating-a-pull-request/) könnte da für dich interessant sein.

Das Issue selbst ist natürlich valide und sollte gefixt werden.
Wie ich sehe hast du das bereits schon gemacht/versucht in #375. Ich werde mir das mal zwischendurch ansehen.

**Comment by M4LuZ** [comment]
Hi Andy,

Danke für die Antwort hier.
Ich hätte jetzt was wegen falscher Erwartungshaltung bei kosmetischen Korrekturen gesagt, aber deine Variante ist besser ;)

Zum Thema: 
Ich habe dunkel im Kopf, dass es eine Funktion für automatische Ersetzung von selbstdefinierten Platzhaltern in Texten in LanSuite gab.
AFAIK hatte ich die für die Implementierung vom GiroCode gekapert.
Ich such gleich mal

**Comment by M4LuZ** [comment]
Korrektur: Die hatte ich dafür geschrieben.
https://github.com/M4LuZ/lansuite/commit/02a193514bc110564dc388b966a77596d1229759

Wenns Sinn macht, die - oder etwas ähnliches - zu übernehmen, dann wäre das eine Lösung für die mangelnde Ersetzung hier

**Comment by HtHNightwolf** [comment]
> Danke für die Antwort hier.
> Ich hätte jetzt was wegen falscher Erwartungshaltung bei kosmetischen Korrekturen gesagt, aber deine Variante ist besser ;)

Alles gut, das hätte ich sogar verdient. Ich wusste nur nicht ob man mich absichtlich ignoriert oder nur nicht gesehen hatte.
Letzten Endes habe ich ja gefunden, wo ich den Code selber einchecke. Ich bin halt kein Entwickler, PHP, mysql & Co. sind überhaupt nicht mein Tagesgeschäft, aber so langsam raffe ich, wie ich mir notfalls selber helfen kann. Wenn ich meine Ergebnisse dann noch der Allgemeinhait vorstellen kann ... umso besser ^.^

Wo das "Use instead." in meinem Beitrag herkommt habe ich zwar nicht verstanden, vermutlich irgendeine Copy-paste-Leiche, aber sei's drum.

Der HTML_NEWLINE-Fehler ist mindestens 4 Jahre alt (seit mind. 2014 drin) und ich dachte mir immer wieder irgendwann muss das doch mal einem auffallen und gefixed werden. Erwartungshaltung geht also auch in beide Richtungen. Auch wenn es nur Kosmetik ist XD

**Comment by andygrunwald** [comment]
@HtHNightwolf Schau dir mal meine Code Änderungen in https://github.com/lansuite/lansuite/pull/378 an. Die sollten das Problem zu sehr großen Teilen lösen. Wäre gut, wenn du das testen könntest.

**Comment by aj-gh** [comment]
Works for me.
Close?

**Comment by M4LuZ** [comment]
> Close?

Works for me ;)
