### ISSUE TITLE
Update PHP Requirements to PHP >= 7.1

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#380]
According to [PHP: Supported Versions](https://secure.php.net/supported-versions.php) our current supported PHP Version 7.0 has only Security Support Until 3 Dec 2018.

Questions:
1. Should we drop support for PHP 7.0, because it will get EOL in December?
2. Should we move the requirements to PHP 7.1?
3. Should we move the requirements to PHP 7.2 directly and skip PHP 7.1 to only support active PHP versions?

I would love to get your opinion about it.
My answers are:

1. Yes
2. Yes
3. I am also fine for this.

**Comment by M4LuZ** [comment]
Closing as PR #402 was merged

**Comment by andygrunwald** [comment]
We are on the way to upgrade to PHP 8.
Closing this issue due to being obsolete.
