### ISSUE TITLE
Internal Links not "resolved"

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#381]
When entering an internal link into a board thread (or Info page or wherever), it is not being resolved as a link. Instead after saving it shows like this and is not clickable:
[url=index.php?mod=seating&action=show&step=2&blockid=6]Testlink[/url] 

In german is easyer: Lansuite erkennt Links, die beginnen mit [url=index.php... nicht als gültigen code und zeigt die daher nicht als Link an, sondern gibt sie stumpf als Text aus.

Once I add the https://domain.com to the URL then it is shown properly as a link that can be clicked. Bad thing is, that I need the "internal Link" functionality to be able to switch the page to LAN-mode (and host it on another domain (url).

## Expected Behavior
If entering an internal link then it should re resolved as a link.

## Current Behavior
Links (without https://domain.com/ suffix) are not being resolved.
This worked some years ago already, I have used it in my 2014 and 2015 version successfully.

## Possible Solution
Programming into the system that a link that start with [url=index.php? ... is being resolved as a link.

## Steps to Reproduce (for bugs)

Here is a sample of a non-working link and one that I manually "fixed".
https://gybralanre.de/index.php?mod=board&action=thread&tid=134

1. Edit a Board thread
2. Highlight a word that is supposed to become a link
3. Click "interner Link" and choose a destination
4. Save the thread
5. look at the text that is supposed to be a link. It is not. Instead it is a string showing: [url=index.php...

## Context
Moving the site to a different url (eg. for lan mode) is not possible with these links

## Your Environment

* Version used: (where do I find that info?) It is from mid-2018!
* Operating System and version: Some Linux, latest patch level
* Enabled features: if required, please ask and I will list.

**Comment by HtHNightwolf** [comment]
*bump*

... auch wennich dann wieder Ärger bekomme ;)

**Comment by M4LuZ** [comment]
> 
> 
> _bump_
> 
> ... auch wennich dann wieder Ärger bekomme ;)

Nö, du wirst nur ignoriert, weil keine Priorität und workaround mit html-code verfügbar ;)

**Comment by andygrunwald** [comment]
Sorry. Ich hab gerade auch sehr wenig Zeit mich darum zu kümmern.
Es ist nicht so, als dass uns das nicht interessiert. Ganz im Gegenteil. Es ist sehr sinnvoll, dass wir über solche Fehler bescheid wissen.
Dennoch ist besonders in der Weihnachtszeit die verfügbare Zeit um solche Fehler zu beheben, nicht wirklich vorhanden.
Deswegen bitte ich/bzw. wir um Nachsicht.

**Comment by HtHNightwolf** [comment]
Moin ihrs, darf ich das nochmal bumpen, bitte?
Das Nichtauflösen dieser Links ist kein trivialer Fehler und verursacht mit jeder weiteren Verlinkung mehr Chaos. Sobald ich die Haupt-URL auf eine interne wechsle, wird mir mein halbes System um die Ohren fliegen, da ich alle Links künstlich hart verdrahten muss.

**Comment by M4LuZ** [comment]
Moin,

Fehler kann ich bestätigen.
Liegt am RegEx, der benutzt wird, um die URLs umzuparsen. 
Wird halt http/https am Anfang erwartet.
Kann man ändern. 
Aaaaaber:
Das Weglassen des Protokolls öffnet leider Tür und Tor für XSS.
Hab versucht, https://github.com/chriskonnertz/bbcode einzubinden, der hat aber das gleiche Problem.
https://packagist.org/packages/youthweb/bbcode-parser sieht aber erstmal gut aus.
Ich mach mal nen Branch auf für Wagemutige zum testen

**Comment by M4LuZ** [comment]
Ist in https://github.com/lansuite/lansuite/commit/14cecfc987e21e821a210e7a2dcf0e4eb9c1df19 enthalten.
Eigentlich sollte das hier referenziert werden, hab mich aber vertippt :/

**Comment by HtHNightwolf** [comment]
Hm.
Heißt das, man kann es testen, hat dann aber ein Sicherheitsrisiko?

Tip:
Das war früher nicht so, da ging das einfach. Aber in welcher Version ich da unterwegs war, weiß ich nicht mehr und ob es da sicher war, kann ich nicht beurteilen.

**Comment by M4LuZ** [comment]
> Heißt das, man kann es testen, hat dann aber ein Sicherheitsrisiko?

Nein, nicht so weit ich es erkennen kann. 
Die Standardfälle für XSS funktionieren nicht. 
Ist aber wie immer nicht großartig gestestet

**Comment by M4LuZ** [comment]
@HtHNightwolf Feedback appreciated! ;)

**Comment by HtHNightwolf** [comment]
Was soll ich jetzt an Feedback geben? Ich habe bisher verstanden, ist kaputt, schnell und sicher reparieren kann man es nicht.
Ich sehe leider keine Auskunft darüber ob und wie es Pläne gibt es langfristig und sicher zu lösen.

Welche Art von Kommentar wäre denn jetzt erwartet?

**Comment by M4LuZ** [comment]
Also ich hätte zumindest erwartet, dass der Text richtig gelesen wird, zumal du selbst schon bezüglich der Sicherheit der Lösung eine Rückfrage hattest. Habe es zugegebenermaßen nicht unmissverständlich formuliert, aber im Zweifel einfach nachfragen.

> Heißt das, man kann es testen, hat dann aber ein Sicherheitsrisiko?
**Nein, nicht so weit ich es erkennen kann.**
Der Text sollte ja nur sagen, dass man das nicht so einfach machen kann, sondern etwas auf die Implementierung achten muss.
Daher etwas gesucht und **getestet, bis die Standardfälle für XSS nicht mehr funktionieren.**

Dementsprechend ist bestätigt:
* Ja, ist kaputt, weil der Parser das aktuell nicht kann
* Von schnell oder langsam war nirgends die Rede, nur, dass es keine Prio hat
* Ebensowenig war die Rede von nicht sicher reparieren **KÖNNEN**, sondern von von sicher reparieren **MÜSSEN**
* Planung ist nicht notwendig, da bereits seit ein Kadidat für eine Lösung im Branch `fix-381-board-url-parse` auf Validierung durch den submitter wartet. 

Wenn das für dich sauber läuft, dann mache ich einen PR auf, um das ganze zu integrieren.

**Comment by HtHNightwolf** [comment]
> Also ich hätte zumindest erwartet, dass der Text richtig gelesen wird, zumal du selbst schon bezüglich der Sicherheit der Lösung eine Rückfrage hattest. Habe es zugegebenermaßen nicht unmissverständlich formuliert, aber im Zweifel einfach nachfragen.
> 

Okay, eine Antwort schuldig bleiben willte ich nicht. Ich habe es tatsächlich nicht als meine Aufgabe verstanden. O

Ich hatte Eure Antworten bisher verstanden als "Es gib einen experimentellen Fix, kann man so aber noch niemandem zumuten, der keine Ahnung von Webseiten-Sicherheit hat. Wir fixen das und melden uns, kann aber dauern."
Daher habe ich selber einen so bedrohlich klingenden Experimentalzustand gar nicht in Betracht gezogen; ich habe mein Geraffel gerade mühselig EU-DSGVO konform machen lassen. Jetzt meine Live-Seite mit echten Userdaten durch unsichere Testzustände zu kompromittieren wo ich Begriffe wie XSS und RP zum ersten Mal höre, war nicht mein Plan.

Ich glaube ich erkläre mich mal:
Beruflich und privat habe ich sonst, von Lansuite abgesehen, nix mit Programmierung, PHP, HTML, mysql und so zu tun (Batch-Dateien, okay). Daher hilft mir deine Erklärung nur so mäßig, da ich sie schlichtweg nicht verstehe. PR aufmachen und XSS - noch nie gehört, ich google das gleich. Was XSS dann so für "Standardfälle" hat und was es bewirkt, wenn sie "nicht mehr funktionieren" muss ich mit dann zusammenreimen.
Ich bin IT-ler, ja, das hilft beim Verstehen aber als Windows-Domänen-Admin bin ich mit Source-Code, PHP und mysql sowie Webseiten-Hosting (und deren Sicherheit) nicht in Kontakt.

Generell Software-Bugfixing an sich kenne ich nur so:
- Bug melden, möglichst wasserdicht und brauchbar beschreiben.
- Der Entwickler erkennt den Fehler anoder nicht und kümmert sich um die Behebung. Enschließlich Testing.
- Irgendwann kommt dann eine neue Version raus oder ein konkreter Fix (eine Datei die getauscht wird z.B.)

Verstehen was da passiert, was welche Änderung bewirkt und welcher Rattenschwanz da dran hängt, dann noch Sicherheitsrisiken einschätzen und das Zwischendurch-Testen macht der "Hersteller", da nur der das Fachwissen und die Tools dazu hat.

...darum habe ich einfach nicht gerafft, was ihr von mir wollt. Eure Texte habe ich natürlich alle gelesen, sogar mehrfach, da ich immer mal wieder das Lesezeichen aufrufe um zu gucken ob es Neuigkeiten gibt ;)

Zum konkreten Fall:
OK, ich soll das also testen habe ich jetzt glaube ich verstanden (auch wenn das "Tür und Tor für XSS" öffnet und der Branch fpr ganz Mutige ist). Den Test widerum muss ich bei demjenigen in Auftrag geben, der meine Seite seit Neuestem hostet, der macht da irgendwas mit git und Docker und branch und forks ... KA!
Er synced halt irgendwie alles mit einem Linux Befehl runter. 

Ich selber kenne Lansuite nur als "google dir eine Anleitung wie XAMPP installiert wird, lade ein Zip-File runter und pack das in _htdocs_.

Ich leite ihm das mal weiter und melde mich (oder vllt. sogar er?!) mit dem Ergebnis.

**Comment by M4LuZ** [comment]
Closing as issue was fixed with merge of #485 
(feedback about functionality still appreciated)
