### ISSUE TITLE
Fatal error bei Anzeige aller Benutzer/Gäste

### ISSUE THREAD

**Issue by daencore** [lansuite/lansuite#383]
Wenn man sich in der Gästeliste oder im Benutzermanager alle User anzeigen lassen möchte bekommen einige User einen Fatal error.
![bild 3](https://user-images.githubusercontent.com/39373552/50658803-cb32e000-0f9a-11e9-9df7-2fbf3bdc5e65.jpg)

Der einzige unterschied den ich feststellen konnte ist das bei den Usern denen das passiert ein längerer Browser link steht und ich habe keine Ahnung wo der herkommt.

Wenn ich auf Alle User anzeigen Klicke sieht mein Link so aus:
![bild 1](https://user-images.githubusercontent.com/39373552/50658898-177e2000-0f9b-11e9-83c1-4f2567f263ae.jpg)

Wenn die Betroffenen User sich alle User anzeigen lassen wollen sieht der Link so aus:
![bild 2](https://user-images.githubusercontent.com/39373552/50658934-32509480-0f9b-11e9-99eb-c86767f41f7a.jpg)

Der PHP fehler der dann auftritt lautet:
`Fatal error: Uncaught --> Smarty: Unable to load template 'file:design/simple/templates/box_case.htm' <-- thrown in /www/htdocs/w00c2db7/lansuite/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 187`

Das Design `Simple` existiert bei uns nicht und soweit ist mir der Fehler klar. Aber ich verstehe nicht wieso es überhaupt dazu kommt. Habt ihr eine Idee und könnt mir einen Tipp geben? Danke

**Comment by aj-gh** [comment]
Die zusätzlichen Felder alleine dürften nicht das Problem sein; zumindest funktioniert das bei den Lan-Seiten, wo ich es ausprobiert habe (einschließlich eurer).
Der Unterschied entsteht durch Verwendung der unteren Seiten-Auswahl (neben dem CSV-Export-Button). Da sind andere Form-Felder hinterlegt, die vom CSV-Export-Button verwendet werden und die tauchen dann entsprechend leer in der URL auf. Bei der oberen Auswahl passiert das nicht.
Kannst du das irgendwie reproduzieren?

**Comment by aj-gh** [comment]
Auf was ist denn "default_design" in eurer _inc/base/config.php_ gesetzt?

**Comment by daencore** [comment]
> Auf was ist denn "default_design" in eurer _inc/base/config.php_ gesetzt?

Hey, Also in der Config ist das richtige Design namens fraghouse gesetzt.

> Die zusätzlichen Felder alleine dürften nicht das Problem sein; zumindest funktioniert das bei den Lan-Seiten, wo ich es ausprobiert habe (einschließlich eurer).

Ja habe das Problem Temporär so gelöst das ich das Design kopiert habe uns simple genannt habe. So tritt der Fehler nicht mehr auf weil er dann einfach auf das andere Design zugreift. Natürlich keine Schöne Lösung.

> Der Unterschied entsteht durch Verwendung der unteren Seiten-Auswahl (neben dem CSV-Export-Button). Da sind andere Form-Felder hinterlegt, die vom CSV-Export-Button verwendet werden und die tauchen dann entsprechend leer in der URL auf. Bei der oberen Auswahl passiert das nicht.
> Kannst du das Problem irgendwie reproduzieren?

Nun das ist mir gar nicht aufgefallen aber tatsächlich scheint es nur das untere Auswahl Feld zu betreffen. Da kann ich den Fehler jetzt reproduzieren. Ich habe eigentlich immer oben getestet und da taucht der Fehler nicht auf. Also muss es etwas mit diesen Form-Feldern zu tun haben?

Danke
