### ISSUE TITLE
Edit User as Admin+

### ISSUE THREAD

**Issue by makno** [lansuite/lansuite#384]
## Expected Behavior

Changing user settings i.e. type user to admin should work flawless.

Currently,  'CheckValidUsername' and 'CheckValidEmail' as well as the second Email field to check valid mails, don't work.

## Current Behavior

Errors prevent from saving are 'User already exists', 'Email already exists' and that the second email is not equal to the first entry. (Because 2nd is empty by default)

## Possible Solution

$mf->AddField(t('Benutzername '.$auth['type']), 'username', '', '', $optional); // MAKNO removed last argument: ,'CheckValidUsername'
$mf->AddField(t('E-Mail'), 'email', '', '', '');  // MAKNO removed last argument: , 'CheckValidEmail'
// MAKNO because it doesn't work:  $mf->AddField(t('E-Mail wiederholen'), 'email2', '', '', '');

## Your Environment

* Version used: 5.0-dev
* Operating System and version: Debian
* Enabled features: Default

**Comment by aj-gh** [comment]
I think the whole email- and username verification needs a review.
ea88add6fbf5775586887c80e95eea7a2bd999e8 introduces the email2 field. By a quick look this already seems to break the newmail function of the mail module when it's enabled for unauthenticated users as that uses the same CheckValidEmail function:https://github.com/lansuite/lansuite/blob/db4b61f3d97dae0069476a061c2acacc639a2cd5/modules/mail/newmail.php#L116
For usrmgr - if an admin modifies an user email2 won't be set (unless the admin is really bored), so this should be bypassed for edits as long as the email address itself is not being modified.
#368 introduces checks for duplicate usernames and email addresses which would theoretically also affect mail/newmail (as above). If I'm not mistaken this also introduces issues for admin edits as the username always exists unless it was just modified in that call by the admin.

Not sure what the best way forward would be.

I guess the duplicate-checks should be moved into separate validation routines if possible and only trigger when they make sense. The email verification field (email2) could probably be validated in MasterForm similar to passwords where this is triggered via a "IS_NEW_PASSWORD" flag - this would also remove the rather ugly access to $_POST in the generic validation function.

Ideally the goal would be that both validations and duplicate-checks are still in place for new user registrations and for modifications if that particular field is being modified, restoring both user modification functionality and mail functions for non-authenticated users (if enabled).
