### ISSUE TITLE
No releases available for package "pear.php.net/PHP_CodeSniffer"

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#394]
## Expected Behavior

Travis runs ;)

## Current Behavior

It seems that the Pear repo for PHP_CodeSniffer is dead

## Possible Solution

Switch to composer for it as require_dev dependency?

## Steps to Reproduce (for bugs)

1. Commit something
2. See Travis log

## Context
Unable to merge anything into master

**Comment by andygrunwald** [comment]
Fixed. Thank you :)
