### ISSUE TITLE
Introduction of composer

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#4]
[Composer](https://getcomposer.org/) is quite the standard when it comes to package management in the PHP world.
The open source community has build a bunch of package that solve common problems like communicating with other services via HTTP (e.g. [guzzle](https://packagist.org/packages/guzzlehttp/guzzle)), working on a console (e.g. [symfony/console](https://packagist.org/packages/symfony/console)), use auth providers like google, etc.
The main sources for those packages are [Packagist](https://packagist.org/) and [Github](https://github.com/).

## Suggestion

My proposal is to introduce composer to the LANSuite codebase.
It don't need to be a 100% integration from the start. It will be a working progress, but to adding it and start with the autoloader might be a first good thing.

## Benefits of this

* Write less code ourselves
* Be able to use external developed and maintained and proven packages from others
* Slim the lan suite codebase and less code to maintain

## Possibilities of this

* Extract every module to a composer package (like the [Symfony framework](https://symfony.com/components) is doing this with their components), with this we have a core and the modules splitted
* Enable "modules" developed by others without modification of the core system
* Enable "themes" developed by others

## How do we come to a conclusion to solve this ticket?

In my opinion this has to be a decision of the main contributors. I would encourage them to post their **+1 for composer introduction** or a **-1 for stay with the current solution** here.

**Comment by M4LuZ** [comment]
Agreement here.
Biggest advantage I see is that we can manage external dependencies with it without having to include all their code into the repository.
As per modules and themes: Not sure that composer is the right solution for that, but to be discussed ;)

**Comment by andygrunwald** [comment]
Great!
I might start with a simple and kind of *quick* addition of composer here with the replacement of some dependencies for `ext_scripts` folder (of there are replacements on packagist)

**Comment by lxp** [comment]
First step is done in #81 by moving the Smarty dependency to composer.

**Comment by andygrunwald** [comment]
composer was introduced already.
We will do more in future, like #100.
So i think this ticket can be closed. If you have still comments, feel free to comment here and we will re open it.
