### ISSUE TITLE
Translation loading broken for generic/global translations

### ISSUE THREAD

**Issue by aj-gh** [lansuite/lansuite#415]
## Expected Behavior

Translations from generic/global translation files such as `inc/language/System_translation.xml` or `inc/language/DB_translation.xml` should be properly read, parsed and used.

## Current Behavior

It seems these files are only read when the translation-mode is "xml" before the database is configured. Afterwards they seem to be no longer read and used.
Also if they are read it seems they end up in a cache but are not called because the cache is built around the module name which doesn't seem to match on these generic/global translations (but I didn't investigate this further).

## Possible Solution

Translation code needs some rework.
See also #344.

## Steps to Reproduce (for bugs)

Switch language to anything but German and notice that even the most basic translations contained in these generic files are not applied.

## Context

My assumption would be that the System/DB translations are supposed to fill in for very common phrases that shouldn't be put into each modules separate translation file. Well, this currently doesn't seem to work that way.

## Your Environment

* Version used: 5.0-dev / Master
* Operating System and version: Debian 9 / Docker from Master

**Comment by M4LuZ** [comment]
Fixed with merge of #650
