### ISSUE TITLE
Implement general caching mechanism

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#432]
## Expected Behavior

LS should provide a general cache functionality to store a set of data with a timeout.
This could use a local file, a db table or APCu//memcache when enabled.

## Current Behavior

Separate implementations everywhere.
* Discord (see #422)
* TS3 (see #292)
* Smarty (although not sure if we can integrate this)
* Maps - potentially (see #301)
* Partyinfo (see #428)

## Possible Solution

implement a new core class for this, that automatically determines the best storage system and then provides an interface to get, store, update and remove datasets based on a key.
Could also include a callback function to refresh data content after timeout has elapsed to make autorefresh on a schedule possible

**Comment by Dwarfex** [comment]
Just a tought:
A proposed solution should use either the [PSR-6](https://www.php-fig.org/psr/psr-6/) (Caching Interface) or the [PSR-16](https://www.php-fig.org/psr/psr-16/) (Simple Cache Interface) for easy and interchangeable chacing.
