### ISSUE TITLE
Check for line length limit (PSR-2) - how to handle violations?

### ISSUE THREAD

**Issue by BenniGotchi** [lansuite/lansuite#442]
## Expected Behavior

To be discussed here in this issue ;)

## Current Behavior

With implementation of #403 Code Style checks for PSR-1 and PSR-2 are applied to all modified php files only, but the former existig exceptions were dropped.

Idea is, that unchanged files are still allowed to hold some CodeStyle exceptions, but all files that are touched, should be modified according to the current code styling rules.
In principle a good approach, I would say. 

But there is now a check active, where I would like to see a discussion for: 
The PSR-2 states for the line length:

    The soft limit on line length MUST be 120 characters; 
    automated style checkers **MUST warn but MUST NOT error** at the soft limit.

This is also, what the automatic checks do - they raise a Warning for these violations.
But the Travis-CI job returns a fail because of these warnings.

In #403 @andygrunwald mentioned, that in almost every IDE there are auto formatting features present, that can help for getting the coding standard fulfilled.
I have some doubts, that they will help for the line length.
 * All the code was put through automated code reformatting tools already, but they obviously didn't take care about (all) long lines
 * I tried the 'Format' feature in the  Eclipse PDT - didn't help.

So I think keeping up this strict handling for the line length would mean a lot of manual editing for the people, who want to contribute.
Worst case they get bored, because they want to contribute a small change but would need to fix a lot of other stuff not really related to the original topic...

## Possible Solution

accept warning for the line length in the automatic checks ?

Propose IDE setups, where the Code style rules are already checked before committing changes.
This would make it much easier, to fix deviations 'on the fly' ?

**Comment by M4LuZ** [comment]
As noted in #403: I suspected that the line length warnings (or any warnings in general) may need exclusion again. 
Happy to have rather good code/documentation than proper formatting, because that can be fixed automatically at any case

**Comment by BenniGotchi** [comment]
Would this also be an option to go for:

     phpcs --runtime-set ignore_warnings_on_exit 1

This would not disable the length check at all, but warnings will not lead to a fail of the automated tests any more.

**Benefit I see:** the warnings would still be part of the logs, thus if someone is interested in cleaning up the code, he can do so.
**Downside** (not sure if it's really a big one): Has an effect on all warnings, not only the LineLength check

I performed a local phpcs run on my pc and regarding Warnings (limited to the modules folder) I could see:

    2080x  Warning: Line exceeds 120 characters; contains 122 characters 
       2x  Warning: Usage of ELSE IF is discouraged;   use ELSEIF instead
      31x  Warning: Method name "_xxx" should not be prefixed with an underscore to indicate visibility

**Comment by M4LuZ** [comment]
> So I don't really see any 'critical' warnings here, that would rectify the failing of the automated tests, or?

Code style checks are never critical by definition, as they only complain about style, not functionality ;)

But out of the three issues found only the line length is found very often and at the end of the day inconsequential.
Both ELSE IF/ ELSEIF and the naming do make some sense to enforce, so I would keep them in

**Comment by BenniGotchi** [comment]
OK, I agree to your arguments. Therefore also the pull request looks good to me.
May I also do the formal act of the code review there?

**Comment by M4LuZ** [comment]
> May I also do the formal act of the code review there?

sure, go for it! ;)
