### ISSUE TITLE
When uploading a Picture the File Permission is 0

### ISSUE THREAD

**Issue by NewbieStriker** [lansuite/lansuite#443]
When uploading a Picture in the Board, User Avatar or something like this the File will be uploaded but the permission is 0 and the picture would not be shown on the page.

When I change the file permission manually on file manager (webhosting) the picture can opened by clicking on the picture. 
When uploading a new file (jpg, gif, png, ...) the error with 0 permission comes again.

Because no file permissions is set the cms shows the following php error:
**Could not open source file 'ext_inc/board_upload/...**
and
**PHP Warning: imagecreatefrompng(ext_inc/board_upload/Googlemap.PNG): failed to open stream: Permission denied in /home/getpcch/public_html/funlan.ch/htdocs/lansuite/inc/Classes/GD.php on line 294**

When I change the permissions on the folder "ext_inc" to subfolders and files to 777 the problem would not be fixed for new uploads.

I had the problem only on a webspace with linux OS (PHP 7.x and 5.6) with Maria DB 10.1.

I tried on a own webserver (intranet) for development at Windows 10 with Xamp 7.3 (Apache 2.4, PHP 7.3.0 and Maria DB 10.1.18) and there was no error.

The Support from my Webhoster said they cannot find any problems and I should ask the developer of lansuite for support. 
But I think it's a problem with permissions or gd extension settings on the webspace.

I worked with newest lansuite image from github (from 28. March 2019)

Can anybody help me?

Thank you for any help.

**Comment by M4LuZ** [comment]
I suspect that your issue is not in regard to file access rights, but rather upper/lowercase handling under linux.
Please try uploading the file as googlemaps.png and see if that works for you. 
If it does, then I think I know where to look...

**Comment by NewbieStriker** [comment]
Hi M4LuZ
You got it. Thank you veru much.

It was the second -> config.php
the part in [lansuite] was empty. Just the default design was set.
