### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by BlackPhoenixAustria** [lansuite/lansuite#453]
Hello my friends,

i have upload the files via ftp, now when i open the site (/install.php) i see the error: 
Fatal error: Uncaught Error: Call to undefined function dependencyPreCheck() in /homepages/21/d800954093/htdocs/lan2019/install.php:7 Stack trace: #0 {main} thrown in /homepages/21/d800954093/htdocs/lan2019/install.php on line 7

When i open the normal site i see the error:
Fatal error: require(): Failed opening required '/homepages/21/d800954093/htdocs/lan2019/vendor/autoload.php' (include_path='.:/usr/lib/php7.3') in /homepages/21/d800954093/htdocs/lan2019/index.php on line 3

What is the problem?
Please help me!

Best regards

**Comment by M4LuZ** [comment]
You missed the initial step in the preparation of the Git image for deployment: Getting the required dependencies and generating the autoloader via composer. 
Refer to the documentation at https://lansuite.github.io/lansuite/docs/installation.html for this
