### ISSUE TITLE
Change design of navigation

### ISSUE THREAD

**Issue by mazzo-** [lansuite/lansuite#477]
Hi,

where can I control the appearance of the menu for a custom template? 

Marcel

**Comment by M4LuZ** [comment]
Hi @mazzo- 

not sure what you mean?
Are you asking about modifying the entries (what is shown in what order for whom), the way entries are generated (do something else than a list of items) or the design applied (how do the entries look)?

**Comment by mazzo-** [comment]
Hi @M4LuZ,

i want to know where the entries getting generated.
E.g. making a dropdown navigation.

**Comment by M4LuZ** [comment]
The related code can be found in `/modules/boxes/Classes/Menu.php` in function `get_menu_items()`
Hope that helps?
