### ISSUE TITLE
New box area

### ISSUE THREAD

**Issue by mazzo-** [lansuite/lansuite#480]
Hi,

i want add more space for boxes, like e.g. boxes in a footer.
How can i declare these areas like {$MainLeftBox}

Marcel

**Comment by M4LuZ** [comment]
Boxes are only supported on the left and right side with the current functionality.
Placing content in the footer requires _at least_ overwriting the footer template (see `design/templates/footer.htm`) and writing the related code for generation (either by extending the existing Boxes module or by placing the related code somewhere)
