### ISSUE TITLE
Backwards compatibility vs. Breaking changes

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#5]
LANSuite was developed some years ago. A few team mates agreed to modernize the code base.

## Possibilities

In my opinion there are two possibilties:

1. Keep Backwards compatibility
2. Breaking changes

### Backwards compatibility

We strength our trust in the userbase.
The userbase knows "lansuite is stable and i can upgrade to every version i want and it don't break"

### Breaking changes

We are able to move fast. Introduce changes. New APIs. New Features.
Sometimes it is necessary to introduce a breaking change to fix a bug properly, because it was a former design decision or something different.

## Ways to communicate it properly

The versioning scheme of a software can be used to communicate a breaking change properly.
[Semantic Versioning](http://semver.org/) is one option to do this.
Your software follows a principle like MAJOR.MINOR.BUGFIX
When the software raises the MAJOR version it indicates that there might be a breaking change in the API.

Another / additional idea to this are upgrade documents next to the code.
The Symfony Framework is doing this. See their [UPGRADE-3.0.md](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md) file for example.
Every breaking change is communicated and a upgrade path is written down.
For people who worked with our API they are aware what to do when upgrade to a newer version

## How do we come to a conclusion to solve this ticket?

In my opinion this has to be a decision of the main contributors. I would encourage them to post their **+1 to be open for breaking changes and communicate them properly** or a **-1 for stay with the current state and maintain backwards compatibility for a long time** here.

## My opinion

To move fast and be able to introduce changes, i am open for breaking changes under the rule that those needs to be documented and easy to follow for other people / endusers.

**Comment by jannaahs** [comment]
Well I started reviewing the merge request and noticed a lot of empty functions and out commented php code. I will continue reviewing after I know if I can delete those lines of code.

**Comment by andygrunwald** [comment]
In my opinion we can cleanup those things directly after the open PRs are merged.
To detect code might be a quick work. Commented can be dropped immediately.
The empty functions need to removed from the code as well.

**Comment by M4LuZ** [comment]
In order for this to work we would first need to define what functions we consider as core API.
And set the correct visibility to enforce encapsulation of non-api functions
We should also question if we even need an API definition if both core and modules are managed by us.

**Comment by andygrunwald** [comment]
The issue here is: In Lansuite there is (nearly) no usage of `private` or `protected`.
Means in theory everything is core api, because everything is public by default.

From a first look i would say `inc/classes` is the core API for now.
For a proper API definition, there needs to be quite some refactoring which might be show up on they way.

Would you agree here?

**Comment by andygrunwald** [comment]
No action since April 2017 here.

@M4LuZ raised a valid point. But this API needs to be defined. I think we should define this API while developing LanSuite further (like we do right now). This will form naturally and we will create a stable API over time. To reach this goal, we need to have some breaking changes (e.g switching a method from public to protected/private).

If no concern comes in anymore, i will close this ticket on 1st April 2018.

**Comment by andygrunwald** [comment]
No new concerns. Closed. See my last comment.
