### ISSUE TITLE
Proposal: Using Symfony HttpFoundation Component to have a unified way to deal with Requests, Responses, Sessions and URL-Generation

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#571]
This is a proposal on introducing a new 3rd party code component into LANSuite: **Symfony HttpFoundation Component**

## Current Behavior

Right now we have all sort of direct access to global variables like `$_GET`, `$_POST`, ... in the codebase. The access is scattered around the whole codebase.

Similar for operations that generate the final response.

> In PHP, the request is represented by some global variables (`$_GET`, `$_POST`, `$_FILES`, `$_COOKIE`, `$_SESSION`, ...) and the response is generated by some functions (`echo`, `header()`, `setcookie()`, ...).

## Expected Behavior

For code consistency, code quality, and security purpose, it would be beneficial to have a single entry (`Request`) and exit (`Response`).

## Possible Solution

> The Symfony HttpFoundation component replaces these default PHP global variables and functions by an object-oriented layer.

## Positive side effects

* Unified access to the session
* [Anonymizing IP Addresses](https://symfony.com/doc/current/components/http_foundation.html#anonymizing-ip-addresses)
* [Setting Cookies](https://symfony.com/doc/current/components/http_foundation.html#setting-cookies)
* [Managing the HTTP Cache](https://symfony.com/doc/current/components/http_foundation.html#managing-the-http-cache)
* [Generating Relative and Absolute URLs](https://symfony.com/doc/current/components/http_foundation.html#generating-relative-and-absolute-urls)
 
## References

* [The HttpFoundation Component documentation](https://symfony.com/doc/current/components/http_foundation.html)
* [symfony/http-foundation @ GitHub](https://github.com/symfony/http-foundation)

**Comment by M4LuZ** [comment]
I would say we can close this one, as the framework is there and we're actively using it
