### ISSUE TITLE
Rewrite oder inkrementelle Verbesserung?

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#574]
## Kontext

LANSuite hat bereits ein paar Jahre auf dem Buckel. Dies sieht man auch an der Code-Base, Design und Co. Die Funktionen sind immer noch klasse, doch kommt es mehr und mehr zu verschiedenen Herausforderungen. Einige habe ich unten aufgelistet.

Durch drei Proposals (https://github.com/lansuite/lansuite/issues/573, https://github.com/lansuite/lansuite/issues/572 und https://github.com/lansuite/lansuite/issues/571) gab es ein Kommentar zum Thema, ob es ein Rewrite geben sollte. Siehe https://github.com/lansuite/lansuite/issues/573#issuecomment-1548005734
Dieses Issue ist genau für diese Diskussion.

## Aktuelle Herausforderungen

* Weiterentwicklung ist nicht wirklich aktiv
* Aktuelle Entwicklungsumgebung lässt dich nicht mehr auf modernen, ARM basierten Rechnen ausführen (aufgrund von fehlenden ARM-Docker-Containern)
* Die Codebase basiert auf Versionen (PHP, MySQL), die bereits den End of Life-Zyklus erreicht haben
* LANSuite selbst ist (meiner Meinung nach) zu überlastet - Ich denke, dass Jeder so seine "Stamm-Module" hat
* Designs sind nicht mehr Zeitgemäß, auch Mobil ist die Seite schwer zu bedienen
* Sicherheitslücken sind mit hoher Wahrscheinlichkeit ebenfalls vorhanden
* Codebase ist an vielen Teilen sehr undurchsichtig / unnötig komplex - Eine erweiterte Aufteilung in Komponenten würde dies erleichtern

### Rewrite

Ein kompletter Rewrite wäre die Möglichkeit auf ein aktuelles Systems aus Unterbau zu wechseln (Symfony oder Laravell).
Dies würde uns sehr viele Möglichkeiten zur Nutzung anderer Open Source Komponenten ermöglichen, was ggf. vieles einfacher machen würde (Login, Auth, Forms, ...).

Der Nachteil wäre ein kompletter Stillstand und bis es zu einer ersten nutzbaren Version kommt, wird es auch dauern. Weiterhin, sofern die Entwicklung im Team stattfindet, müssen diverse Entscheidungen getroffen werden. Die Erfolgsrate bei solch großen Rewrites in einem Open Source Team halte ich für gering.

Auch die Rückwärtskompatibilität ist eine Herausforderung. Zumindest das DB-Schema wäre sinnvoll, zu supporten, damit Updates auf den Rewrite möglich sind.

### Inkrementelle Verbesserung

Stück für Stück-Verbesserungen wären auch möglich.
Den Unterbau komplett durch ein Framework zu ersetzen ist sehr hoher Aufwand.
Durch Projekte wie Symfony Components kann jedoch ein Teil sinnvoller Funktionen genutzt werden.

Vorteil wäre ein lauffähiges System, und die User könnten Stück für Stück mit der neuen Version mitgehen.

Nachteil wäre, dass man nie auf einen komplett aktuellen Stand kommen würde.

## Nutzung des Projektes

Eine Frage ist auch, was es für Open Source Alternativen für LAN Parties gibt und ob man sich diese ansieht oder LANSuite weiter führt.

## Bitte um Feedback und eure Meinung

Lasst mich doch mal wissen was ihr denkt.

**Comment by andygrunwald** [comment]
Related: https://skamille.medium.com/avoiding-the-rewrite-trap-b1283b8dd39e

**Comment by M4LuZ** [comment]
Also related: https://www.youtube.com/watch?v=AbSehcT19u0 in regards to current state

Also wenn sich nicht 2-3 Studenten mit mehr als genug Freizeit und Motivation finden, ist ein rewrite eigentlich vom Tisch.

Alternativen soweit bekannt sind eigentlich nur dotlan (wobei das nmE auch moderierter Stillstand ist) und Byceps (was wegen der Konzeptionierung als Python-Daemon eigentlich nicht mit klassischen webhosting läuft und daher nicht die gleiche Zielgruppe abdeckt)

Ergo gibt es mehr als genug Bedarf hierfür.

Bleibt ein iterativer Ansatz.
Fies sind hier nur die diversen internen harten Abhängigkeiten, man muss also etwas grübeln, wie man das hinbekommt.

Die beste Idee, die ich bis jetzt hatte, war die Kernfunktionaltität neben der vorhandenen Funktionalität neu zu entwickeln (hauptsächlich die globalen Objekte, installation, setup + update) und dann die Module nacheinander neu aufzusetzen.
Was uns in der Zwischenzeit leider vom am-leben-halten nicht entbindet.

**Comment by andygrunwald** [comment]
Scheint als haben wir da eine gewisse Einigkeit. Wäre cool die Meinung von @byte666 auch zu hören.

### MySQL + MariaDB

Ich selbst mache einen Software Engineering Podcast ([Engineering Kiosk](https://engineeringkiosk.dev/)) und habe dazu gerade erst eine Episode aufgenommen: [#69 MySQL vs. MariaDB](https://engineeringkiosk.dev/podcast/episode/69-mysql-vs-mariadb/).
Die Unterschiede werden immer mehr und die DBs driften weiter Auseinander.
Meiner Meinung nach sollten wir uns auf eine Variante comitten und diese supporten.
Viele Standard-Webhoster bieten MySQL an. Für unsere Zwecke reicht dies vollkommen.
Natürlich kann man auch anfangen beides zu supporten, aber aktuell sehe ich den Need dafür nicht und das führt ggf. zu einer weiteren erhöhten Komplexität. Speziell wenn wir JSON oder GEO Funktionen nutzen wollen (da unterscheiden die sich enorm).

### Inkrementelle Verbesserung

Meiner Meinung nach sollten wir mehr dazu übergehen, "proven" Komponenten von großen Projekten zu nutzen, siehe
* https://github.com/lansuite/lansuite/issues/571
* https://github.com/lansuite/lansuite/issues/572
* https://github.com/lansuite/lansuite/issues/573

Auch wenn Sie am Anfang nicht "die Welt" bewegen, macht es dies nicht nur für uns einfacher, sondern ggf. auch für externe Contributor.
Zusätzlich sind das Komponenten, die auch sehr viele Bugfixes von der Community bekommen.

Dazu zählt natürlich auch ein modernes Environment mit PHP und MySQL Versionen, die offiziell supported sind.
Besonders wenn man mit Docker entwickelt (wie ich zB) gibt es bei älteren Versionen keine Docker Images für die ARM-CPU Architektur (aka mac M1).

Wenn Ihr damit OK seid, würde ich damit Stück für Stück beginnen und hier und da mal in die Richtung gehen.

**Comment by andygrunwald** [comment]
Ich glaube dieses Ticket können wir schließen, weil die Entscheidung für eine inkrementelle Verbesserung gefallen ist
