### ISSUE TITLE
Lansuite Zukunft?

### ISSUE THREAD

**Issue by byte666** [lansuite/lansuite#64]
Mal eine allgemeine Frage. Was passiert denn hier gerade? Was is das Ziel? Ich hab x-Mails bekommen und hab keinen Überblick. Auf der Orgapage steht dazu nix. Und wie bekomm ich Zugriff das ich unsere ganzen Fixes hochladen kann? Leider hat sich der der GIT-Umstellung einiges angestaut.

**Comment by jannaahs** [comment]
> Mal eine allgemeine Frage. Was passiert denn hier gerade? Was is das Ziel? 

Wir wollen Lansuite auf einen aktuelleren Stand der Technik bringen.
Langfirstig gehören dazu im Groben:
- Code Qualität erhöhen
- moderners Design
- bessere Dokumentation

> Und wie bekomm ich Zugriff das ich unsere ganzen Fixes hochladen kann?

@andygrunwald wie bekommen wir extrene Änderungen am besten mit rein?

**Comment by M4LuZ** [comment]
> @andygrunwald wie bekommen wir extrene Änderungen am besten mit rein?
Extern? Der Kollege ist mehr intern als wir alle zusammen ;)
Und der Prozess ist ja separat schon besprochen worden:

- In Fork committen, 
- Merge request machen,
- Review, 
- Rein in master.

**Comment by jannaahs** [comment]
@M4LuZ Mit extern meine ich,  dass es bis jetzt in keinem Repository liegt und wir es nicht reinmerken können. Sorry für die ungünstige Wortwahl ;)

Ich würde diesen Vorgang in der Rede festhalten. Da @byte666 nicht der einzige sein wird, der weiterentwickelt hat.

**Comment by andygrunwald** [comment]
Fühlt euch frei @byte666 als Contributer oder Admin hier einzutragen :)

Wegen dem mergen der Ändrungen:
Das ist immer etwas tricky.
Wir haben auf der einen Seite das Git-Repository. Auf der anderen Seite einen Code-Stand der (wohlmöglich) unversioniert ist. Oder @byte666 liegt der in SVN oder einem anderen Versionskontrollsystem?

Natürlich kann man die beiden Stände gegeneinander stellen und [diffen](https://wiki.ubuntuusers.de/diff/).
Die Herausforderung ist dabei, die einzelnen Änderungen mit einem Kontext und einer Beschreibung wieder zu versehen. Weil ich gehe davon aus, dass 50 Änderungen gemacht wurden. Und Änderung 1 wegen eines Fehlers in Module A und Änderung 40 wegen eines neuen Features im Core gemacht wurden. Diese alle als "Änderungen von alter Version" zu comitten wäre möglich, aber fragwürdig.

@byte666 Kannst du deinen aktuellen Stand mal in ein eigenes Github-Repository überführen? Auf [Guides @ Github: Hello World](https://guides.github.com/activities/hello-world/) ist beschrieben wie du das machst. Dabei lernst man auch Grundzüge von Git (ich weiß leider nicht wie viel du schon davon weißt).

Dann könnte man sich deine Änderungen mal ansehen und ggf. einen Diff sowie [Pull Requests](https://help.github.com/articles/about-pull-requests/) erstellen.

Wäre das eine Option?

Alternativ kannst du es mir auch per zip zukommen lassen (email Adresse findest du in meinem Profil). Dann kann ich das für dich übernehmen. Kann aber ein paar Tage dauern.

**Comment by andygrunwald** [comment]
@byte666 Ist die Frage hier beantwortet und kann das Ticket geschlossen werden? Oder ist noch was offen?

**Comment by andygrunwald** [comment]
Kein Feedback nach ~2 Wochen.

@byte666 Wenn du noch Fragen/Anmerkungen hast oder Hilfe wahrnehmen möchtest, melde dich :) Oder öffne das Ticket einfach erneut. Ich schließe es nun (vorerst), damit wir, wenn wir durch den Issue Tracker gehen, immer und immer wieder über das Ticket gucken.
