### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by jannaahs** [lansuite/lansuite#66]
Meantioned in #64 
Add a guide for contribution in the Readme or GitPages?

**Comment by andygrunwald** [comment]
I would prefer to add the contribution guide into the README.md.

Why?
If you want to contribute, most of the time you will have a look at the README anyway.
The website / github pages is mostly the point of contact where a user has the first contact with the application itself. At this site the user decided if he/she continues or go away.
Questions like "What is lansuite?", "How does it look like?", "What is it good for?", etc. will be answered.

Next point: The contribution guide should be located in the source code / next to the source code.
This guide might change. And if this guide is located in another repository or in another branch (`gh-pages`), we might oversee this.

If someone wants to contribute he/she will dive deeper.

Just my 2 cents.

**Comment by jannaahs** [comment]
We now have such a guide. See #71 for more information.
