### ISSUE TITLE
Documentation of classes and interfaces

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#68]
@byte666 wrote in Ticket #6:

> What about documenation of the classes? I think thats also a important part of styling guides. In the past I have added many doxygen/phpdocumentor compartible dokumentation. Encapsulate the stuff in classes and documentation was (and is still) a base part to get a stable Lansuite. One of my last actions was to create more classes with clear interfaces and expand the pluginsystem. And there you need a good interface description.

I created a new ticket to discuss this (suggested by @M4LuZ in #6).

My 2 cents on this topic:
I agree with @byte666 here, but i think you are mixing several topics together:

### Class / Interface / Application-Architecture

You mentioned that during your last actions you created more classes with a clear interface. That is really great and necessary. Especially when we want to reuse the code. And good interface design is really difficult. Mostly those kind of action is bundled with a usage of a certain Design Pattern.
So: Thanks for the effort! I hope you are able to contribute more of those to lansuite :)
Would love to see this

### Documentation of Classes / Interfaces

Of course, one part of a style guide or one part of software development at a certain level is the documentation of a class / interface including their single methods and properties.
This is necessary and should be done.
The most common way in PHP is due to the usage of doc blocks like

```php
<?php

/**
 * Interface Foo is doing X Y and responsible for Z
 */
interface Foo {

    /**
     * My function is calculating the length of $bar and addint $baz on top.
     * Why? Because someone said so.
     * 
     * @param string $bar
     * @param int $baz
     * @return string
     */
    public function myFunction($bar, $baz);
}
```

And with the usage of annotations like `@param`, `@return`, etc.
Nearly every IDE or standard tool is able to understand those.

### Documentation of the architecture

To document the bigger architecture and the correct usage and combination of multiple interfaces and classes is a different part of the documentation. But important as well.
But i would prefer to put this into a more "prosa" text instead of doc blocks.

This kind of documentation is mostly part of a design document or part of a guide like "How to write a plugin".
One example could be the [Best Practice of the Bundle guide from Symfony](https://symfony.com/doc/current/bundles/best_practices.html).

### Format of the documentation

I mentioned different types of documentation: Code / interface documentation and architecture / design documentation.

#### Code / interface documentation

This part should be part of the code and next to the class as doc blocks. If someone changes the class, the docs are changed immediately. Even a proper IDE marks this via a red underline.
If someone wants to have this documentation in a CSH, HTML or PDF format, he/she is free to trigger a phpDocumentator or DocOxygen or another tool that is able to generate these kind or reports.

Right now we have this kind of documentation checked in into the `docs/`-Folder.
From my perspective we can delete those. Why? Not because i don't see a reason.
Because to keep them up to date we need to compile those *with every commit* when we change a function, delete a function, change the docs of the function, etc.
This would create a huge overhead. Even more, if we have multiple PRs pending and each PR contain such a generated documentation, we are not able to merge them, because they are conflicting in Git.

What would be a valid alternative is to generate those docs for every stable release of lansuite.
Means: We are planing to release a new stable version (e.g. after a LAN party). We make a new git branch, generate those docs, commit them, create a git tag and zip those into a release package.

With this we would combine both worlds and have both advantages.

#### Architecture / design documentation

This kind of documentation should be written down in a more prosa text way. This text can explain how the code is structured, what make sense to implement and why, etc.

Where to store those information is a good question.
A wiki (e.g. here in github) might be a good choice. Personally i prefer a `docs/design/...`-Folder in the code / next to the code. There we can put Markdown or Restructured Text files to explain these.
The big benefit of this kind of format is: We can generate them into several formats like PDF, a book, HTML or whatever via [Git book](https://www.gitbook.com/) or [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html).

**Of course: I am open for discussion :)**

**Comment by M4LuZ** [comment]
In general I agree with all points, would just do it slightly different:
**Functional documentation:** 
Should be in the source code, yes.
Release versions should contain a generated document, otherwise we should provide an online version *somewhere* that is autogenerated from the the repository on each change.
I consider "generate it yourself" not very end-user friendly in that regard.
**Architecture documentation:** 
I have a very positive experience with being able to include pictures and (plant)UML diagrams into the architecture documentation. 
It would be advantageous if we can contain the documentation with the code, but I wouldn't sacrifice graphical representations for that.
If we can have both, then perfect ;)

**Comment by andygrunwald** [comment]
Fine for me :)

**Comment by andygrunwald** [comment]
This is ongoing anyways during the development (for the source code documentation).
We improve it on the road.

For the architecture documentation, we continue the discussion in #214 and #123
If someone has concerns or more feedback, feel free to add a comment here and we will reopen the issue.
