### ISSUE TITLE
Uncaught TypeError: check_birthday()

### ISSUE THREAD

**Issue by buzanits** [lansuite/lansuite#718]
When adding a user account an error occurs

## Expected Behavior

No error

## Current Behavior

```
Fatal error: Uncaught TypeError: check_birthday(): Return value must be of type string|bool, none returned in /var/www/virtservers/web_210/modules/usrmgr/Functions/CheckBirthday.php:24 Stack trace: #0 [internal function]: check_birthday('1970-4-9') #1 /var/www/virtservers/web_210/inc/Classes/MasterForm.php(614): call_user_func('check_birthday', '1970-4-9') #2 /var/www/virtservers/web_210/modules/usrmgr/add.php(304): LanSuite\MasterForm->SendForm('index.php?mod=s...', 'user', 'userid', '') #3 /var/www/virtservers/web_210/modules/signon/show.php(7): include_once('/var/www/virtse...') #4 /var/www/virtservers/web_210/index_module.inc.php(111): include_once('/var/www/virtse...') #5 /var/www/virtservers/web_210/index.php(416): include_once('/var/www/virtse...') #6 {main} thrown in /var/www/virtservers/web_210/modules/usrmgr/Functions/CheckBirthday.php on line 24
```

## Possible Solution

The function `check_birthday()` is defined to return only boolean or string, but it returns null if the first `if` does not apply, because there is no `else` branch for that. Fix: add `else return false`;

## Steps to Reproduce (for bugs)

1. Open Lansuite without being logged in
2. Add a user account
3. Save
4.

## Your Environment

* Version used: 4.2
* Operating System and version: Debian 10.13
* Enabled features:

**Comment by andygrunwald** [comment]
Thanks @buzanits

Sadly, you have merged the fix only in your branch.
I created a PR in https://github.com/lansuite/lansuite/pull/725 for the main version.
