### ISSUE TITLE
Check required, if account was already registered with a given email adress

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#72]
I just had a case where a user created three accounts with the same username and email address.
It seems that uniqueness of neither username nor email address is currently enforced.
But this should be the case for at least one of them. Which one is up for discussion, as both have their advantages and disadvantages

## Expected Behaviour
Entered user data should be checked against existing users and uniqueness of either username or email address should enforced. Both on application and database level.

## Current Behaviour
Users are able to create additional accounts with the same username and email address.
Those get a new userid assigned. It has not been tested what account is picked for login when the correct credentials are entered

## Possible Solution

Entered user data should be checked against existing users.
Uniqueness of either username or email address should be enforced. 
Preferably both on application and database level.

## Steps to Reproduce (for bugs)

Create a new user, use same data as for one of the existing ones

## Context

This is needed to reduce the amount of dead accounts in the system and make it easier for both guests and administrators to find the right user account for a given username / email address

## Your Environment

* Version used: GIT:maluz/master
* Operating System and version: Win10
* Enabled features:

**Comment by jannaahs** [comment]
> # Possible Solution
>Entered user data should be checked against existing users.
>Uniqueness of either username or email address should be enforced.
>Preferably both on application and database level.

The email address must be unique, because you can login with your email address.

**Comment by M4LuZ** [comment]
> The email address must be unique, because you can login with your email address.

That is true, but we could do either.
While the email address is used for login, only the username is used for selection dialogues and display (e.g. tournament, forum...)

If we allow the same username multiple times, then we need to think about how to allow the user to reliably identify another user account.

**Comment by JochenJung** [comment]
Sounds like a good idea to make the username unique as well. Though that might cause issues when updating..

**Comment by M4LuZ** [comment]
It certainly will. 
It shouldn't be to hard to identify all conflicts, and there are multiple ways how we could deal with it:
* We could provide a function that allows merging and renaming of user accounts. That would (together with a check for duplicate usernames / email adresses) allow the manual cleaning of the user database.
* Or we could just provide a cleanup scricpt, that automatically attaches a number or random string to the username with the higher user id (first come, first serve). That wouldn't solve the email addresses though. There it is either merge or delete. But I suspect that on multiple use of an email adress only one of the accounts will be actually used, so it may be quite simple to remove all but the one that actually saw a logon of the user.
* Or we just provide a list of conflicting user accounts and leave it for the site admins to sort out (the lazy variant ;))
Any additional solutions?

**Comment by M4LuZ** [comment]
After a quick rethought I would propose to do the following:
* Add a check on login if username / mail matches more than one account. Add a log message in this case.
* Add a check in the registration from if the same username or email is already in use. Deny account creation if that is the case
* And if there is enough time: Create a user-merge function.

**Comment by byte666** [comment]
This discussion is many years old. ;)  For registration you can't use the the eMail twice i think. In our system we get an error. (maybe we already fix this at synlan this but i believe to remember Jochen do this many years ago in LS base). 

Proposal for registration : integrate check for mail AND username but make it configurable via the $cfg part of Lansuite. ("mail" always, "user" configurable but default off?). Simple and flexible. 

In the past i build a little script to find duplicate Users/Adresses for LS (mit dem Levensteingerümpel). Maybe i found this in the deep of my data black holes. I also tried code a merge form. (compare fields line-by-line old/new and select one for merge with checkbox etc.) The form was not the Problem, but a consistent/stable way to find all links with userids to rewrite after merge. (modules, different id key's etc.) But not impossible. :)

**Comment by M4LuZ** [comment]
@byte666 Any chance to get your code so that we don't need to re-develop this?

**Comment by M4LuZ** [comment]
Had now a go at this and it seems that uniqueness of the email is already enforced by the masterform.
At least for self-registering. It may still be off if the quick sign-in is used.
But developed everything according to the discussion.
I would suggest that we add a quick pre-upgrade check to inform the user if he has multiple accounts for one email (should be a `SELECT email,count(*) as qty from %prefix%user group by email`)
