### ISSUE TITLE
Add continuous integration checks

### ISSUE THREAD

**Issue by lxp** [lansuite/lansuite#85]
As the general agreement is to have common coding style in the project, we should have automated checks that enforce the code style, as well as, do other tests.

## Expected Behavior

For each pull request there should be automated checks for
* code style
* syntax

## Current Behavior

No checks are made.

## Possible Solution

Integrate Travis CI to run our checks.
We should start with some easy checks, just to have Travis integration and improve the checks later.

## Context

I am trying to improve code quality and make it easier for people to contribute to the project.

**Comment by lxp** [comment]
Thanks for merging, we still need to enable Travis-CI for the main repository.
@JochenJung I think you are currently the only one that can do that?

Please see https://docs.travis-ci.com/user/getting-started
Summary:
- Sign in to Travis CI with your GitHub account, accepting the GitHub access permissions confirmation.
- Once you’re signed in, and we’ve synchronized your GitHub repositories, go to your profile page and enable Travis CI for the open source repository you want to build.

**Comment by andygrunwald** [comment]
@lxp Done a second ago: https://travis-ci.org/lansuite/lansuite

**Comment by lxp** [comment]
@andygrunwald Thank you, for implementing it so fast :)
