### ISSUE TITLE
Move issues from the http://lansuite.orgapage.de/-Bugtracker to Github

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#9]
The current bugtracker is located at http://lansuite.orgapage.de/.
The code moved to Github and now to this organisation.

One question comes into mind: Should we move all issues from the former bugtracker to github?
In my opinion there are two options:

1. We transfer everything and try to fix them
2. We make a cut and say "when it is important, it will come back"

Personally i prefer option 2. Especially if we decide to remove deprecated functionality and accept breaking changes. Because from a fast look, many of those issues are related to older setups. Those will disappear with those changes.

Because this ticket exists in the former repository as well, @jannaahs posted that he agrees on the second option as well.

What the others think about this?

**Comment by jannaahs** [comment]
I want to share my two important aspects why we should use github.
1. We will propably recode some modules or change the archtecture not knowing which bugs will still occure.
2. Github gives us the possibility to manage the bugs as issues, sort them by labels and assign contributors to them. Therefore we don't need an extra installation of lansuite to track those bugs.

**Comment by andygrunwald** [comment]
Good points @jannaahs. I 100% agree.

**Comment by andygrunwald** [comment]
@M4LuZ @JochenJung What are your opinions here?

**Comment by JochenJung** [comment]
One idea with the Lansuite bugtracker was the feature donations. I don't think GitHub has that option. On the other hand there hasn't been a donation for quite a while now. So the concept seems to be not working anyhow,.

And as most developers are used to the GitHub bugtracker, I agreee that it might be a good idea to use a system the people are used to.

**Comment by andygrunwald** [comment]
For donations there are several platforms out there like https://www.patreon.com/ that are used within open source already.
This can be integrated if someone is willing to do so.

@JochenJung It is possible to provide me access / grants to the bugtracker at Orgapage?
My username is `andygrunwald` and i want to go through the tickets and may close or fix them.

**Comment by andygrunwald** [comment]
And it is possible to write a news in orgapage, that the project has moved to github?

**Comment by JochenJung** [comment]
You now have all the rights granted.

Feel free to clean up the bugtracker and post some news.

**Comment by M4LuZ** [comment]
So...
Seems that the page is now down and a redirect is active.
Whats the plan about doing this here then without any access to the old system?

**Comment by andygrunwald** [comment]
I think then this can be closed.
An alternative would be to ask for a database dump and extract the issues there. But the question is if this effort is worth it. We could also take the easy route and say "What important is comes back anyway".

**Comment by andygrunwald** [comment]
See my last comment.
When there is anything left, feel free to reopen this.
