### ISSUE TITLE
Turnierplan zeigt kein Datum

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#902]
Ich bin gerade gefragt worden woran man erkennen soll, an welcher Wochentag gemeint ist mit den Uhrzeiten, die man sieht, wenn man auf "Turniere-->Zeitplan" klickt.
Gute Frage, da sind nur Uhrzeiten.

## Expected Behavior
Nicht nur Uhrzeit, sondern auch Datum des gemeinten Tages einblenden.

## Current Behavior
Kein Datum eingblendet, nur Uhrzeit (aber von welchem Tag?).

## Possible Solution
Datum und Uhrzeit einblenden oder einen Tab pro Datum.

## Steps to Reproduce (for bugs)
Click here https://gybralanre.de/index.php?mod=tournament2&action=timetable

## Context
Gäste wissen nicht an welchem Tag um 22 Uhr das Turnier losgeht. Freitag? Samstag? Sonntag (natürlich nicht, aber so weit denken Gäste nicht)?

## Your Environment
Lansuite latest

**Comment by andygrunwald** [comment]
Sehr guter Punkt. Sollten wir machen.

**Comment by M4LuZ** [comment]
PR ist offen.
@HtHNightwolf : Immer her mit Wünschen, Anmerkungen oder Beobachtungen!

**Comment by HtHNightwolf** [comment]
> PR ist offen. @HtHNightwolf : Immer her mit Wünschen, Anmerkungen oder Beobachtungen!
> 
> Und viel Erfolg mit eurer Party, schön zu sehen, dass ihr fast ausgebucht seid

Danke, die restlichen Plätze sind für Euch & Freunde. Also auf, auf!

**Comment by M4LuZ** [comment]
Danke für das Angebot, aber andere Pläne und 400km Entfernung ;)
Aus Interesse: Nutzt ihr eine dezidierte lokale Instanz mit Import/Export oder lauft ihr mit dem Internet-System?

**Comment by M4LuZ** [comment]
PR ist durch.
Wenn ihr weitere Modifikationen vor der Party vermeiden wollt, dann reicht es, in `modules/tournament2/timetable.php` Zeile 48 von 
```
$head .= "<td colspan = 4>". $func->unixstamp2date($z, "time")."</td>"; 
```
zu
```
$head .= "<td colspan = 4>". $func->unixstamp2date($z, "shortdaytime")."</td>";
````
zu ändern. Alles andere ist nur code-refactoring
