### ISSUE TITLE
Blank page on user registration due to datatype mismatch for field `icq`

### ISSUE THREAD

**Issue by M4LuZ** [lansuite/lansuite#925]
## Expected Behavior

Thanks to @JDLPIXEL for the original report

Filling out the user registration form should should either work and throw the user on the index page or show an error message / log what went wrong

## Current Behavior

Registration leads to a blank page due to an underlying SQL error in masterform.
It is tried to write an empty string `''` to field `icq`, but field is defined as `integer`, thus causing an sql-error, leading to a blank page.

## Possible Solution

* Enforce handling of integer fields as such in masterform, may require explicit type-hinting
* Remove field
* switch from masterform to dedicated form, as most of the fields are not needed for registration (or put them on a dedicated tab)
* ensure proper error handling on SQL issues

## Steps to Reproduce (for bugs)

TBD - this may be an instance-specific issue, but it may not

## Context

new users unable to register

## Your Environment

* Version used: git/master
* Operating System and version: deb11/mysql 8.1/php 8.1
* Enabled features:

**Comment by JDLPIXEL** [comment]
Kein Problem :D
Ich hätte noch ein paar mehr Fehler von der Seite,
kann ich dich da irgendwie anderes kontaktieren?
Oder dir ne pm schreiben?

**Comment by M4LuZ** [comment]
>kann ich dich da irgendwie anderes kontaktieren?
Oder dir ne pm schreiben?

Klar, nimm welchen Kanal dir am einfachsten fällt.
Hier als Ticket macht halt erst Sinn, wenn klarsteht, dass es ein generelles Problem und nicht ein spezifisches Problem unserer Instanz ist.

Und vielen Dank fürs Melden, das hilft ungemein!

**Comment by JDLPIXEL** [comment]
> > kann ich dich da irgendwie anderes kontaktieren?
> > Oder dir ne pm schreiben?
> 
> Klar, nimm welchen Kanal dir am einfachsten fällt. Hier als Ticket macht halt erst Sinn, wenn klarsteht, dass es ein generelles Problem und nicht ein spezifisches Problem unserer Instanz ist.
> 
> Und vielen Dank fürs Melden, das hilft ungemein!

Okay perfekt, das Registrieren klappt übrigens wieder!

**Comment by M4LuZ** [comment]
Closed as caused by DB not being up to date

**Comment by JDLPIXEL** [comment]
[Fehler-Berg-Lan.pdf](https://github.com/lansuite/lansuite/files/14474240/Fehler-Berg-Lan.pdf)
@M4LuZ Hier, habe mal alle Fehler die ich auf die Stelle gefunden habe kurz Zusammengefasst

**Comment by M4LuZ** [comment]
@JDLPIXEL Danke, das meiste davon sind einfach nur Warnungen die aktuell noch zum Bugfixing ausgegeben werden, aber keine Probleme verursachen.

Die fehlenden Bilder wurden nicht aus der alten Installation übernommen, sollte jetzt behoben sein.

Für den Error 500 ist ein fix gerade unterwegs, evtl. kontaktiere ich dich dazu separat noch mal

**Comment by JDLPIXEL** [comment]
> @JDLPIXEL Danke, das meiste davon sind einfach nur Warnungen die aktuell noch zum Bugfixing ausgegeben werden, aber keine Probleme verursachen.
> 
> Die fehlenden Bilder wurden nicht aus der alten Installation übernommen, sollte jetzt behoben sein.
> 
> Für den Error 500 ist ein fix gerade unterwegs, evtl. kontaktiere ich dich dazu separat noch mal

@M4LuZ 
Kein Ding,
Das mit den Bildern klappt auf jeden Fall jetzt wieder,
habe mir gerade nochmal die Website was genauer angeschaut.
Habe noch ein paar Fehler & Fehlermeldungen zusammengefasst.
Dass sollte jetzt aber alles sein xD
[Fehler-Berg-Lan-v2.pdf](https://github.com/lansuite/lansuite/files/14478340/Fehler-Berg-Lan-v2.pdf)

**Comment by M4LuZ** [comment]
Wir sind auf dem aktuellen Git Master (Stand Vorgestern), also alles was da auftaucht sollte auch noch im Code vorhanden sein.
Werde aber die Warnings jetzt ausschalten, weil die Seite langsam wieder Endbenutzer-Ready werden muss.

**Comment by JDLPIXEL** [comment]
> Wir sind auf dem aktuellen Git Master (Stand Vorgestern), also alles was da auftaucht sollte auch noch im Code vorhanden sein. Werde aber die Warnings jetzt ausschalten, weil die Seite langsam wieder Endbenutzer-Ready werden muss.

Ahh okay nice! ;)
