### ISSUE TITLE
Remove LGZ-related code

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#940]
## Expected Behavior

Remove all code related to the LGz (LAN Gamer Zone League).
The former URL (http://lan.gamer-zone.com/) is not available anymore.
I could not find any news about the shutdown - However, it is not available anymore.

## Current Behavior

LGz IDs can still be configured.

## Possible Solution

Remove all LGz code, in a similar way like we did for WWCL and NGL:

- https://github.com/lansuite/lansuite/issues/252
- https://github.com/lansuite/lansuite/issues/932

## Context

@M4LuZ Do you have more information about LGz? Or are you fine with removing it?

**Comment by M4LuZ** [comment]
That one is also dead and the URL is for purchase at http://lan.gamer-zone.com/
so fine to continue with removal

**Comment by andygrunwald** [comment]
@M4LuZ Would you find time to review the existing pull requests?
There are many outstanding lines of code changed. Removing LGZ would be highly likely to conflict with existing changes.

E.g. https://github.com/lansuite/lansuite/pull/939
