### ISSUE TITLE
Blank page before installing a new lansuite - can't run installer

### ISSUE THREAD

**Issue by lbayerlein** [lansuite/lansuite#95]
## Expected Behavior

Untar it on my system and launch web browser for installing lansuite.

## Current Behavior
Untar it on my system and look at a white screen. I am using a CentOS 7 with all updates (7.4.1708 Core) and PHP FPM from the remi repo with PHP 7.0.26. Every time, I wanted to access lansuite on this server, following error message comes up:

> [Mon Dec 04 07:03:55.745038 2017] [proxy_fcgi:error] [pid 18961] [client X.X.X.X:38682] AH01071: Got error 'PHP message: PHP Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/lansuite/inc/classes/class_db_mysql.php on line 166\nPHP message: PHP Warning: mysqli_free_result() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/lansuite/inc/classes/class_db_mysql.php on line 203\n'

## Possible Solution
Can't answer this

## Steps to Reproduce (for bugs)

1. Install CentOS 7 and update it
2. Install PHP7 FPM (package: php70-php-fpm) with all dependencies like php70-php-{snmp,gd,mysql}
3. Install Apache from the repo and configure to use php-fpm
4. Get the v4.2 of lansuite from github, extract it to the web directory and try to run it on the browser

## Your Environment

* Version used: actual lansuite release (v4.2)
* Operating System and version:
  * CentOS Linux release 7.4.1708 (Core) 
  * Apache/2.4.6 (CentOS)
  * PHP 7.0.26 (cli) (built: Nov 21 2017 14:27:35) ( NTS )
* Enabled features:

**Comment by andygrunwald** [comment]
Confirmed bug as well. It seems that you have solved this / found a work around. Is this true? If yes, can you write down how?

**Comment by lbayerlein** [comment]
No I don't have found a workaround. I am using a unsupported version of php (5.4) and it is only a technical working solution for successfully running lansuite. But if I activate php >5.6, a white page comes up and that's it. Even after installing lansuite with php5.4 and switching to php7.0 a white page comes up.

**Comment by andygrunwald** [comment]
Thx for the feedback. I will check it out.

**Comment by lbayerlein** [comment]
If it would be helpful, I could provide a virtualbox image to speed up your testings?

**Comment by andygrunwald** [comment]
@lbayerlein We use Docker for this purpose, no need from your site to put the extra effort in. Thanks anyway.

How did you manage #96 if you are not able to install it?

**Comment by lbayerlein** [comment]
@andygrunwald with php-fpm, you can really easy switch through all php versions. The base version delivered by CentOS is php5.4. Now lansuite runs with php5.4 in our environment.

**Comment by M4LuZ** [comment]
The most current version of LanSuite (4.2) is incompatible with PHP 7
The required fixes are in the Git master branch, but we have yet to create a new official release.
So for now you either have to use the Git Master (and pull in missing requirements via composer) or stay at PHP 5.X

**Comment by rlc-gamer** [comment]
I found a workaround. 
First download Smarty in Version 3 from [Smarty](https://www.smarty.net/download)
2. Upload it to `/inc/classes/Smarty`
3. Open /index.php and add Line 241
`require('inc/classes/Smarty/Smarty.class.php');`
Working for me with PHP 7

**Comment by M4LuZ** [comment]
> Working for me with PHP 7

I would say that if it works for you with PHP 7 then you aren't using the latest lansuite release 4.2, but the Git version instead. 
And in that case I suspect you missed the part that you have to pull in the dependencies via `composer up`
As that does install Smarty in the correct version for you.

Am I guessing correctly?

Nevertheless there is an issue with the installer that it only throws blank screens instead of helpful error messages, see #149 for reference

**Comment by M4LuZ** [comment]
Closing this, as no further feedback has been provided and the basic issue (blank screen without error details) has been fixed with #149
