### ISSUE TITLE
TLD .bayern domain not accepted

### ISSUE THREAD

**Issue by lbayerlein** [lansuite/lansuite#96]
## Expected Behavior
Register with domain.bayern without an error

## Current Behavior
Top level domain .bayern not accepted

## Steps to Reproduce (for bugs)

1. Register on a fresh installation on lansuite with a .bayern domain

## Your Environment
It is an default behaviour and not only in my environment.

**Comment by andygrunwald** [comment]
Thanks for the report. Indeed, new TLDs are not (yet) supported. This needs to be fixed asaps.

**Comment by M4LuZ** [comment]
We did merge support for checks against the official TLD-list a while ago, but this is only used for email address verification so far.
See 
https://github.com/lansuite/lansuite/commit/8b4959bdf4894757cde2c899ddcad97ef3b61c1a
https://github.com/lansuite/lansuite/commit/b550e4764714957961e7ff4d9fe497cd018a5292
I guess it would also make sense to include a refresh on install to make sure the referenced list is up to date.

**Comment by andygrunwald** [comment]
@M4LuZ Why we are doing this at all? Any special reason for it? What use case it is for?

**Comment by M4LuZ** [comment]
Why: To fix the existing address verification, as it had an incomplete and outdated list of TLDs to check against. 
Instead of just adding whatever was needed in that case I suggested to go all the way and make it future proof by getting the most current TLD list directly from IANA.  
As said this would also work for stuff like .bayern, .nrw and whatever somebody comes up with in the future.
Usecase: Avoid (at least some) typing mistakes.

**Comment by andygrunwald** [comment]
I would vote for dropping the specific list of TLDs at all and use standard verification mechanism to check the email.
Why? In the future more and more TLDs will come up. If someone want to run a version that is older that the new TLDs, but want to run this under a new TLD this might raise problems for the user.

What is the alternative?
I would vote for the need to enter the Address / E-Mail-Address twice. This lowers the risk of typos. Further more we can use libs like [symfony/validator](https://github.com/symfony/validator) ([docs](https://symfony.com/doc/current/components/validator.html)) to check the validation of the address / e-mail address here.

This behaviour is pretty standard in the internet.

With this solution we

* are able to drop the tld mysql table at all
* reduce the need of a constant cronjob to update the tlds
* make it easier for the user to run whatever TLD he/she wants

Even better: If someone is running a custom tld inside their network (i know some companies who are doing this for internal services), this would be possible with the approach suggested in this comment. With the IANA list, it would not.

When i have a little bit time, i might prepare it and you can see the solution.
What do you think?

@lbayerlein As a quick fix:

1. Connect to your MySQL database. You can do this with tools like MySQL Workbench
2. Fire this query to enable the `bayern` TLD
```sql
INSERT INTO ls_tlds (`tld`) VALUES ("bayern");
```

(If you prefix for your tables is not `ls`, change it to yours).

Does this work for you?

**Comment by lbayerlein** [comment]
Perfect thank you :)

**Comment by M4LuZ** [comment]
I agree on @andygrunwald proposal.
It is a shame to remove relatively new contribution for the TLD functionality, but I do see that this could cause more harm than good

**Comment by BenniGotchi** [comment]
I also agree on @andygrunwald's proposal.

**Comment by byte666** [comment]
There is an update script (ext_scripts\update_tlds.php) but i prefer also general/simple solutions. In summary more stable.

**Comment by andygrunwald** [comment]
Reopened, because i think we can make this check a little bit more stable and backup with unit tests.

@lbayerlein The initial bug was fixed in #186. Can you check this again?

**Comment by andygrunwald** [comment]
See #202 for another PR on this topic.
