### ISSUE TITLE
mysqli_num_rows, mysqli_free_result expects parameter 1

### ISSUE THREAD

**Issue by schitzN** [lansuite/lansuite#97]
Servus,

hab laufend wie oben beschriebene Error-Meldungen. Hab gesehen, dass in eurem alten Bugtracker das Problem auch schon angesprochen wurde (bug #1172).

**Comment by andygrunwald** [comment]
@schitzN Kannst du uns folgende Infos geben?

- PHP-Version
- Klickpfad / Test zur Reproduktion
- Link zum alten Bug-Ticket
- Genutzte PHP-Version

**Comment by schitzN** [comment]
Servus,

habs mit php 5.6, 7.0 und 7.1 probiert.
MySQl version 5.7
Link: best-designs.at/lan
bugtracker:
http://lansuite.orgapage.de/index.php?mod=bugtracker&bugid=1172&ms_page=0

Andy Grunwald <notifications@github.com> schrieb am So., 17. Dez. 2017,
13:37:

**Comment by andygrunwald** [comment]
Im stats-Modul habe ich einen solchen Fehler gefunden.
Dieser wird / wurde hier behoben: https://github.com/lansuite/lansuite/pull/108

Kannst du mal einen Screenshot von dem Fehler machen?
Oder ist das ggf. schon der Fehler, den ich gefixt habe?

**Comment by andygrunwald** [comment]
@schitzN Ich habe das Problem befunden und in PR https://github.com/lansuite/lansuite/pull/111 behoben.
Ich warte noch auf einen Review und dann wird es in das LanSuite übernommen.
